// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIstioGateways implements IstioGatewayInterface
type FakeIstioGateways struct {
	Fake *FakeIstioV1
	ns   string
}

var istiogatewaysResource = v1.SchemeGroupVersion.WithResource("istiogateways")

var istiogatewaysKind = v1.SchemeGroupVersion.WithKind("IstioGateway")

// Get takes name of the istioGateway, and returns the corresponding istioGateway object, and an error if there is any.
func (c *FakeIstioGateways) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.IstioGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(istiogatewaysResource, c.ns, name), &v1.IstioGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IstioGateway), err
}

// List takes label and field selectors, and returns the list of IstioGateways that match those selectors.
func (c *FakeIstioGateways) List(ctx context.Context, opts metav1.ListOptions) (result *v1.IstioGatewayList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(istiogatewaysResource, istiogatewaysKind, c.ns, opts), &v1.IstioGatewayList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.IstioGatewayList{ListMeta: obj.(*v1.IstioGatewayList).ListMeta}
	for _, item := range obj.(*v1.IstioGatewayList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested istioGateways.
func (c *FakeIstioGateways) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(istiogatewaysResource, c.ns, opts))

}

// Create takes the representation of a istioGateway and creates it.  Returns the server's representation of the istioGateway, and an error, if there is any.
func (c *FakeIstioGateways) Create(ctx context.Context, istioGateway *v1.IstioGateway, opts metav1.CreateOptions) (result *v1.IstioGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(istiogatewaysResource, c.ns, istioGateway), &v1.IstioGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IstioGateway), err
}

// Update takes the representation of a istioGateway and updates it. Returns the server's representation of the istioGateway, and an error, if there is any.
func (c *FakeIstioGateways) Update(ctx context.Context, istioGateway *v1.IstioGateway, opts metav1.UpdateOptions) (result *v1.IstioGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(istiogatewaysResource, c.ns, istioGateway), &v1.IstioGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IstioGateway), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIstioGateways) UpdateStatus(ctx context.Context, istioGateway *v1.IstioGateway, opts metav1.UpdateOptions) (*v1.IstioGateway, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(istiogatewaysResource, "status", c.ns, istioGateway), &v1.IstioGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IstioGateway), err
}

// Delete takes name of the istioGateway and deletes it. Returns an error if one occurs.
func (c *FakeIstioGateways) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(istiogatewaysResource, c.ns, name, opts), &v1.IstioGateway{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIstioGateways) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(istiogatewaysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.IstioGatewayList{})
	return err
}

// Patch applies the patch and returns the patched istioGateway.
func (c *FakeIstioGateways) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.IstioGateway, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(istiogatewaysResource, c.ns, name, pt, data, subresources...), &v1.IstioGateway{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.IstioGateway), err
}
