// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMCompressors implements ASMCompressorInterface
type FakeASMCompressors struct {
	Fake *FakeIstioV1
	ns   string
}

var asmcompressorsResource = v1.SchemeGroupVersion.WithResource("asmcompressors")

var asmcompressorsKind = v1.SchemeGroupVersion.WithKind("ASMCompressor")

// Get takes name of the aSMCompressor, and returns the corresponding aSMCompressor object, and an error if there is any.
func (c *FakeASMCompressors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMCompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmcompressorsResource, c.ns, name), &v1.ASMCompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCompressor), err
}

// List takes label and field selectors, and returns the list of ASMCompressors that match those selectors.
func (c *FakeASMCompressors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMCompressorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmcompressorsResource, asmcompressorsKind, c.ns, opts), &v1.ASMCompressorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMCompressorList{ListMeta: obj.(*v1.ASMCompressorList).ListMeta}
	for _, item := range obj.(*v1.ASMCompressorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMCompressors.
func (c *FakeASMCompressors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmcompressorsResource, c.ns, opts))

}

// Create takes the representation of a aSMCompressor and creates it.  Returns the server's representation of the aSMCompressor, and an error, if there is any.
func (c *FakeASMCompressors) Create(ctx context.Context, aSMCompressor *v1.ASMCompressor, opts metav1.CreateOptions) (result *v1.ASMCompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmcompressorsResource, c.ns, aSMCompressor), &v1.ASMCompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCompressor), err
}

// Update takes the representation of a aSMCompressor and updates it. Returns the server's representation of the aSMCompressor, and an error, if there is any.
func (c *FakeASMCompressors) Update(ctx context.Context, aSMCompressor *v1.ASMCompressor, opts metav1.UpdateOptions) (result *v1.ASMCompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmcompressorsResource, c.ns, aSMCompressor), &v1.ASMCompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCompressor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMCompressors) UpdateStatus(ctx context.Context, aSMCompressor *v1.ASMCompressor, opts metav1.UpdateOptions) (*v1.ASMCompressor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmcompressorsResource, "status", c.ns, aSMCompressor), &v1.ASMCompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCompressor), err
}

// Delete takes name of the aSMCompressor and deletes it. Returns an error if one occurs.
func (c *FakeASMCompressors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmcompressorsResource, c.ns, name, opts), &v1.ASMCompressor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMCompressors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmcompressorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMCompressorList{})
	return err
}

// Patch applies the patch and returns the patched aSMCompressor.
func (c *FakeASMCompressors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMCompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmcompressorsResource, c.ns, name, pt, data, subresources...), &v1.ASMCompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCompressor), err
}
