// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMGrpcJsonTranscoders implements ASMGrpcJsonTranscoderInterface
type FakeASMGrpcJsonTranscoders struct {
	Fake *FakeIstioV1
	ns   string
}

var asmgrpcjsontranscodersResource = v1.SchemeGroupVersion.WithResource("asmgrpcjsontranscoders")

var asmgrpcjsontranscodersKind = v1.SchemeGroupVersion.WithKind("ASMGrpcJsonTranscoder")

// Get takes name of the aSMGrpcJsonTranscoder, and returns the corresponding aSMGrpcJsonTranscoder object, and an error if there is any.
func (c *FakeASMGrpcJsonTranscoders) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMGrpcJsonTranscoder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmgrpcjsontranscodersResource, c.ns, name), &v1.ASMGrpcJsonTranscoder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGrpcJsonTranscoder), err
}

// List takes label and field selectors, and returns the list of ASMGrpcJsonTranscoders that match those selectors.
func (c *FakeASMGrpcJsonTranscoders) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMGrpcJsonTranscoderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmgrpcjsontranscodersResource, asmgrpcjsontranscodersKind, c.ns, opts), &v1.ASMGrpcJsonTranscoderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMGrpcJsonTranscoderList{ListMeta: obj.(*v1.ASMGrpcJsonTranscoderList).ListMeta}
	for _, item := range obj.(*v1.ASMGrpcJsonTranscoderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMGrpcJsonTranscoders.
func (c *FakeASMGrpcJsonTranscoders) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmgrpcjsontranscodersResource, c.ns, opts))

}

// Create takes the representation of a aSMGrpcJsonTranscoder and creates it.  Returns the server's representation of the aSMGrpcJsonTranscoder, and an error, if there is any.
func (c *FakeASMGrpcJsonTranscoders) Create(ctx context.Context, aSMGrpcJsonTranscoder *v1.ASMGrpcJsonTranscoder, opts metav1.CreateOptions) (result *v1.ASMGrpcJsonTranscoder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmgrpcjsontranscodersResource, c.ns, aSMGrpcJsonTranscoder), &v1.ASMGrpcJsonTranscoder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGrpcJsonTranscoder), err
}

// Update takes the representation of a aSMGrpcJsonTranscoder and updates it. Returns the server's representation of the aSMGrpcJsonTranscoder, and an error, if there is any.
func (c *FakeASMGrpcJsonTranscoders) Update(ctx context.Context, aSMGrpcJsonTranscoder *v1.ASMGrpcJsonTranscoder, opts metav1.UpdateOptions) (result *v1.ASMGrpcJsonTranscoder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmgrpcjsontranscodersResource, c.ns, aSMGrpcJsonTranscoder), &v1.ASMGrpcJsonTranscoder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGrpcJsonTranscoder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMGrpcJsonTranscoders) UpdateStatus(ctx context.Context, aSMGrpcJsonTranscoder *v1.ASMGrpcJsonTranscoder, opts metav1.UpdateOptions) (*v1.ASMGrpcJsonTranscoder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmgrpcjsontranscodersResource, "status", c.ns, aSMGrpcJsonTranscoder), &v1.ASMGrpcJsonTranscoder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGrpcJsonTranscoder), err
}

// Delete takes name of the aSMGrpcJsonTranscoder and deletes it. Returns an error if one occurs.
func (c *FakeASMGrpcJsonTranscoders) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmgrpcjsontranscodersResource, c.ns, name, opts), &v1.ASMGrpcJsonTranscoder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMGrpcJsonTranscoders) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmgrpcjsontranscodersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMGrpcJsonTranscoderList{})
	return err
}

// Patch applies the patch and returns the patched aSMGrpcJsonTranscoder.
func (c *FakeASMGrpcJsonTranscoders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMGrpcJsonTranscoder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmgrpcjsontranscodersResource, c.ns, name, pt, data, subresources...), &v1.ASMGrpcJsonTranscoder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGrpcJsonTranscoder), err
}
