// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "istio.io/client-go/asm/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AverageLatencySchedulingPolicies returns a AverageLatencySchedulingPolicyInformer.
	AverageLatencySchedulingPolicies() AverageLatencySchedulingPolicyInformer
	// ConcurrencyLimitingPolicies returns a ConcurrencyLimitingPolicyInformer.
	ConcurrencyLimitingPolicies() ConcurrencyLimitingPolicyInformer
	// ConcurrencySchedulingPolicies returns a ConcurrencySchedulingPolicyInformer.
	ConcurrencySchedulingPolicies() ConcurrencySchedulingPolicyInformer
	// LoadRampingPolicies returns a LoadRampingPolicyInformer.
	LoadRampingPolicies() LoadRampingPolicyInformer
	// Policies returns a PolicyInformer.
	Policies() PolicyInformer
	// RateLimitingPolicies returns a RateLimitingPolicyInformer.
	RateLimitingPolicies() RateLimitingPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AverageLatencySchedulingPolicies returns a AverageLatencySchedulingPolicyInformer.
func (v *version) AverageLatencySchedulingPolicies() AverageLatencySchedulingPolicyInformer {
	return &averageLatencySchedulingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ConcurrencyLimitingPolicies returns a ConcurrencyLimitingPolicyInformer.
func (v *version) ConcurrencyLimitingPolicies() ConcurrencyLimitingPolicyInformer {
	return &concurrencyLimitingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ConcurrencySchedulingPolicies returns a ConcurrencySchedulingPolicyInformer.
func (v *version) ConcurrencySchedulingPolicies() ConcurrencySchedulingPolicyInformer {
	return &concurrencySchedulingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LoadRampingPolicies returns a LoadRampingPolicyInformer.
func (v *version) LoadRampingPolicies() LoadRampingPolicyInformer {
	return &loadRampingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Policies returns a PolicyInformer.
func (v *version) Policies() PolicyInformer {
	return &policyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RateLimitingPolicies returns a RateLimitingPolicyInformer.
func (v *version) RateLimitingPolicies() RateLimitingPolicyInformer {
	return &rateLimitingPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
