// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"istio.io/client-go/asm/pkg/clientset/versioned/scheme"
	"net/http"

	v1 "istio.io/api/ampere/v1"
	rest "k8s.io/client-go/rest"
)

type AmpereV1Interface interface {
	RESTClient() rest.Interface
	AverageLatencySchedulingPoliciesGetter
	ConcurrencyLimitingPoliciesGetter
	ConcurrencySchedulingPoliciesGetter
	LoadRampingPoliciesGetter
	PoliciesGetter
	RateLimitingPoliciesGetter
}

// AmpereV1Client is used to interact with features provided by the ampere group.
type AmpereV1Client struct {
	restClient rest.Interface
}

func (c *AmpereV1Client) AverageLatencySchedulingPolicies(namespace string) AverageLatencySchedulingPolicyInterface {
	return newAverageLatencySchedulingPolicies(c, namespace)
}

func (c *AmpereV1Client) ConcurrencyLimitingPolicies(namespace string) ConcurrencyLimitingPolicyInterface {
	return newConcurrencyLimitingPolicies(c, namespace)
}

func (c *AmpereV1Client) ConcurrencySchedulingPolicies(namespace string) ConcurrencySchedulingPolicyInterface {
	return newConcurrencySchedulingPolicies(c, namespace)
}

func (c *AmpereV1Client) LoadRampingPolicies(namespace string) LoadRampingPolicyInterface {
	return newLoadRampingPolicies(c, namespace)
}

func (c *AmpereV1Client) Policies(namespace string) PolicyInterface {
	return newPolicies(c, namespace)
}

func (c *AmpereV1Client) RateLimitingPolicies(namespace string) RateLimitingPolicyInterface {
	return newRateLimitingPolicies(c, namespace)
}

// NewForConfig creates a new AmpereV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*AmpereV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new AmpereV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*AmpereV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &AmpereV1Client{client}, nil
}

// NewForConfigOrDie creates a new AmpereV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AmpereV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AmpereV1Client for the given RESTClient.
func New(c rest.Interface) *AmpereV1Client {
	return &AmpereV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AmpereV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
