// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/versioned/scheme"
	"context"
	"time"

	v1 "istio.io/api/ampere/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RateLimitingPoliciesGetter has a method to return a RateLimitingPolicyInterface.
// A group's client should implement this interface.
type RateLimitingPoliciesGetter interface {
	RateLimitingPolicies(namespace string) RateLimitingPolicyInterface
}

// RateLimitingPolicyInterface has methods to work with RateLimitingPolicy resources.
type RateLimitingPolicyInterface interface {
	Create(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.CreateOptions) (*v1.RateLimitingPolicy, error)
	Update(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.UpdateOptions) (*v1.RateLimitingPolicy, error)
	UpdateStatus(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.UpdateOptions) (*v1.RateLimitingPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.RateLimitingPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RateLimitingPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RateLimitingPolicy, err error)
	RateLimitingPolicyExpansion
}

// rateLimitingPolicies implements RateLimitingPolicyInterface
type rateLimitingPolicies struct {
	client rest.Interface
	ns     string
}

// newRateLimitingPolicies returns a RateLimitingPolicies
func newRateLimitingPolicies(c *AmpereV1Client, namespace string) *rateLimitingPolicies {
	return &rateLimitingPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rateLimitingPolicy, and returns the corresponding rateLimitingPolicy object, and an error if there is any.
func (c *rateLimitingPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RateLimitingPolicy, err error) {
	result = &v1.RateLimitingPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RateLimitingPolicies that match those selectors.
func (c *rateLimitingPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RateLimitingPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RateLimitingPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rateLimitingPolicies.
func (c *rateLimitingPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rateLimitingPolicy and creates it.  Returns the server's representation of the rateLimitingPolicy, and an error, if there is any.
func (c *rateLimitingPolicies) Create(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.CreateOptions) (result *v1.RateLimitingPolicy, err error) {
	result = &v1.RateLimitingPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitingPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rateLimitingPolicy and updates it. Returns the server's representation of the rateLimitingPolicy, and an error, if there is any.
func (c *rateLimitingPolicies) Update(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.UpdateOptions) (result *v1.RateLimitingPolicy, err error) {
	result = &v1.RateLimitingPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		Name(rateLimitingPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitingPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rateLimitingPolicies) UpdateStatus(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.UpdateOptions) (result *v1.RateLimitingPolicy, err error) {
	result = &v1.RateLimitingPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		Name(rateLimitingPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitingPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rateLimitingPolicy and deletes it. Returns an error if one occurs.
func (c *rateLimitingPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rateLimitingPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rateLimitingPolicy.
func (c *rateLimitingPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RateLimitingPolicy, err error) {
	result = &v1.RateLimitingPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ratelimitingpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
