// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/ampere/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConcurrencyLimitingPolicies implements ConcurrencyLimitingPolicyInterface
type FakeConcurrencyLimitingPolicies struct {
	Fake *FakeAmpereV1
	ns   string
}

var concurrencylimitingpoliciesResource = v1.SchemeGroupVersion.WithResource("concurrencylimitingpolicies")

var concurrencylimitingpoliciesKind = v1.SchemeGroupVersion.WithKind("ConcurrencyLimitingPolicy")

// Get takes name of the concurrencyLimitingPolicy, and returns the corresponding concurrencyLimitingPolicy object, and an error if there is any.
func (c *FakeConcurrencyLimitingPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ConcurrencyLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(concurrencylimitingpoliciesResource, c.ns, name), &v1.ConcurrencyLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConcurrencyLimitingPolicy), err
}

// List takes label and field selectors, and returns the list of ConcurrencyLimitingPolicies that match those selectors.
func (c *FakeConcurrencyLimitingPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ConcurrencyLimitingPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(concurrencylimitingpoliciesResource, concurrencylimitingpoliciesKind, c.ns, opts), &v1.ConcurrencyLimitingPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ConcurrencyLimitingPolicyList{ListMeta: obj.(*v1.ConcurrencyLimitingPolicyList).ListMeta}
	for _, item := range obj.(*v1.ConcurrencyLimitingPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested concurrencyLimitingPolicies.
func (c *FakeConcurrencyLimitingPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(concurrencylimitingpoliciesResource, c.ns, opts))

}

// Create takes the representation of a concurrencyLimitingPolicy and creates it.  Returns the server's representation of the concurrencyLimitingPolicy, and an error, if there is any.
func (c *FakeConcurrencyLimitingPolicies) Create(ctx context.Context, concurrencyLimitingPolicy *v1.ConcurrencyLimitingPolicy, opts metav1.CreateOptions) (result *v1.ConcurrencyLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(concurrencylimitingpoliciesResource, c.ns, concurrencyLimitingPolicy), &v1.ConcurrencyLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConcurrencyLimitingPolicy), err
}

// Update takes the representation of a concurrencyLimitingPolicy and updates it. Returns the server's representation of the concurrencyLimitingPolicy, and an error, if there is any.
func (c *FakeConcurrencyLimitingPolicies) Update(ctx context.Context, concurrencyLimitingPolicy *v1.ConcurrencyLimitingPolicy, opts metav1.UpdateOptions) (result *v1.ConcurrencyLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(concurrencylimitingpoliciesResource, c.ns, concurrencyLimitingPolicy), &v1.ConcurrencyLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConcurrencyLimitingPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConcurrencyLimitingPolicies) UpdateStatus(ctx context.Context, concurrencyLimitingPolicy *v1.ConcurrencyLimitingPolicy, opts metav1.UpdateOptions) (*v1.ConcurrencyLimitingPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(concurrencylimitingpoliciesResource, "status", c.ns, concurrencyLimitingPolicy), &v1.ConcurrencyLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConcurrencyLimitingPolicy), err
}

// Delete takes name of the concurrencyLimitingPolicy and deletes it. Returns an error if one occurs.
func (c *FakeConcurrencyLimitingPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(concurrencylimitingpoliciesResource, c.ns, name, opts), &v1.ConcurrencyLimitingPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConcurrencyLimitingPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(concurrencylimitingpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ConcurrencyLimitingPolicyList{})
	return err
}

// Patch applies the patch and returns the patched concurrencyLimitingPolicy.
func (c *FakeConcurrencyLimitingPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ConcurrencyLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(concurrencylimitingpoliciesResource, c.ns, name, pt, data, subresources...), &v1.ConcurrencyLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConcurrencyLimitingPolicy), err
}
