// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/ampere/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRateLimitingPolicies implements RateLimitingPolicyInterface
type FakeRateLimitingPolicies struct {
	Fake *FakeAmpereV1
	ns   string
}

var ratelimitingpoliciesResource = v1.SchemeGroupVersion.WithResource("ratelimitingpolicies")

var ratelimitingpoliciesKind = v1.SchemeGroupVersion.WithKind("RateLimitingPolicy")

// Get takes name of the rateLimitingPolicy, and returns the corresponding rateLimitingPolicy object, and an error if there is any.
func (c *FakeRateLimitingPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RateLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ratelimitingpoliciesResource, c.ns, name), &v1.RateLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RateLimitingPolicy), err
}

// List takes label and field selectors, and returns the list of RateLimitingPolicies that match those selectors.
func (c *FakeRateLimitingPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RateLimitingPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ratelimitingpoliciesResource, ratelimitingpoliciesKind, c.ns, opts), &v1.RateLimitingPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RateLimitingPolicyList{ListMeta: obj.(*v1.RateLimitingPolicyList).ListMeta}
	for _, item := range obj.(*v1.RateLimitingPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rateLimitingPolicies.
func (c *FakeRateLimitingPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ratelimitingpoliciesResource, c.ns, opts))

}

// Create takes the representation of a rateLimitingPolicy and creates it.  Returns the server's representation of the rateLimitingPolicy, and an error, if there is any.
func (c *FakeRateLimitingPolicies) Create(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.CreateOptions) (result *v1.RateLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ratelimitingpoliciesResource, c.ns, rateLimitingPolicy), &v1.RateLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RateLimitingPolicy), err
}

// Update takes the representation of a rateLimitingPolicy and updates it. Returns the server's representation of the rateLimitingPolicy, and an error, if there is any.
func (c *FakeRateLimitingPolicies) Update(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.UpdateOptions) (result *v1.RateLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ratelimitingpoliciesResource, c.ns, rateLimitingPolicy), &v1.RateLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RateLimitingPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRateLimitingPolicies) UpdateStatus(ctx context.Context, rateLimitingPolicy *v1.RateLimitingPolicy, opts metav1.UpdateOptions) (*v1.RateLimitingPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ratelimitingpoliciesResource, "status", c.ns, rateLimitingPolicy), &v1.RateLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RateLimitingPolicy), err
}

// Delete takes name of the rateLimitingPolicy and deletes it. Returns an error if one occurs.
func (c *FakeRateLimitingPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ratelimitingpoliciesResource, c.ns, name, opts), &v1.RateLimitingPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRateLimitingPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ratelimitingpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RateLimitingPolicyList{})
	return err
}

// Patch applies the patch and returns the patched rateLimitingPolicy.
func (c *FakeRateLimitingPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RateLimitingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ratelimitingpoliciesResource, c.ns, name, pt, data, subresources...), &v1.RateLimitingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RateLimitingPolicy), err
}
