// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "istio.io/client-go/asm/pkg/clientset/versioned/typed/ampere/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAmpereV1 struct {
	*testing.Fake
}

func (c *FakeAmpereV1) AverageLatencySchedulingPolicies(namespace string) v1.AverageLatencySchedulingPolicyInterface {
	return &FakeAverageLatencySchedulingPolicies{c, namespace}
}

func (c *FakeAmpereV1) ConcurrencyLimitingPolicies(namespace string) v1.ConcurrencyLimitingPolicyInterface {
	return &FakeConcurrencyLimitingPolicies{c, namespace}
}

func (c *FakeAmpereV1) ConcurrencySchedulingPolicies(namespace string) v1.ConcurrencySchedulingPolicyInterface {
	return &FakeConcurrencySchedulingPolicies{c, namespace}
}

func (c *FakeAmpereV1) LoadRampingPolicies(namespace string) v1.LoadRampingPolicyInterface {
	return &FakeLoadRampingPolicies{c, namespace}
}

func (c *FakeAmpereV1) Policies(namespace string) v1.PolicyInterface {
	return &FakePolicies{c, namespace}
}

func (c *FakeAmpereV1) RateLimitingPolicies(namespace string) v1.RateLimitingPolicyInterface {
	return &FakeRateLimitingPolicies{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAmpereV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
