// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/ampere/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAverageLatencySchedulingPolicies implements AverageLatencySchedulingPolicyInterface
type FakeAverageLatencySchedulingPolicies struct {
	Fake *FakeAmpereV1
	ns   string
}

var averagelatencyschedulingpoliciesResource = v1.SchemeGroupVersion.WithResource("averagelatencyschedulingpolicies")

var averagelatencyschedulingpoliciesKind = v1.SchemeGroupVersion.WithKind("AverageLatencySchedulingPolicy")

// Get takes name of the averageLatencySchedulingPolicy, and returns the corresponding averageLatencySchedulingPolicy object, and an error if there is any.
func (c *FakeAverageLatencySchedulingPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AverageLatencySchedulingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(averagelatencyschedulingpoliciesResource, c.ns, name), &v1.AverageLatencySchedulingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AverageLatencySchedulingPolicy), err
}

// List takes label and field selectors, and returns the list of AverageLatencySchedulingPolicies that match those selectors.
func (c *FakeAverageLatencySchedulingPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AverageLatencySchedulingPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(averagelatencyschedulingpoliciesResource, averagelatencyschedulingpoliciesKind, c.ns, opts), &v1.AverageLatencySchedulingPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.AverageLatencySchedulingPolicyList{ListMeta: obj.(*v1.AverageLatencySchedulingPolicyList).ListMeta}
	for _, item := range obj.(*v1.AverageLatencySchedulingPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested averageLatencySchedulingPolicies.
func (c *FakeAverageLatencySchedulingPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(averagelatencyschedulingpoliciesResource, c.ns, opts))

}

// Create takes the representation of a averageLatencySchedulingPolicy and creates it.  Returns the server's representation of the averageLatencySchedulingPolicy, and an error, if there is any.
func (c *FakeAverageLatencySchedulingPolicies) Create(ctx context.Context, averageLatencySchedulingPolicy *v1.AverageLatencySchedulingPolicy, opts metav1.CreateOptions) (result *v1.AverageLatencySchedulingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(averagelatencyschedulingpoliciesResource, c.ns, averageLatencySchedulingPolicy), &v1.AverageLatencySchedulingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AverageLatencySchedulingPolicy), err
}

// Update takes the representation of a averageLatencySchedulingPolicy and updates it. Returns the server's representation of the averageLatencySchedulingPolicy, and an error, if there is any.
func (c *FakeAverageLatencySchedulingPolicies) Update(ctx context.Context, averageLatencySchedulingPolicy *v1.AverageLatencySchedulingPolicy, opts metav1.UpdateOptions) (result *v1.AverageLatencySchedulingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(averagelatencyschedulingpoliciesResource, c.ns, averageLatencySchedulingPolicy), &v1.AverageLatencySchedulingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AverageLatencySchedulingPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAverageLatencySchedulingPolicies) UpdateStatus(ctx context.Context, averageLatencySchedulingPolicy *v1.AverageLatencySchedulingPolicy, opts metav1.UpdateOptions) (*v1.AverageLatencySchedulingPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(averagelatencyschedulingpoliciesResource, "status", c.ns, averageLatencySchedulingPolicy), &v1.AverageLatencySchedulingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AverageLatencySchedulingPolicy), err
}

// Delete takes name of the averageLatencySchedulingPolicy and deletes it. Returns an error if one occurs.
func (c *FakeAverageLatencySchedulingPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(averagelatencyschedulingpoliciesResource, c.ns, name, opts), &v1.AverageLatencySchedulingPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAverageLatencySchedulingPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(averagelatencyschedulingpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.AverageLatencySchedulingPolicyList{})
	return err
}

// Patch applies the patch and returns the patched averageLatencySchedulingPolicy.
func (c *FakeAverageLatencySchedulingPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AverageLatencySchedulingPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(averagelatencyschedulingpoliciesResource, c.ns, name, pt, data, subresources...), &v1.AverageLatencySchedulingPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AverageLatencySchedulingPolicy), err
}
