// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1beta1 "istio.io/client-go/pkg/apis/istio/v1beta1"
	istiov1beta1 "istio.io/client-go/pkg/applyconfiguration/istio/v1beta1"
	scheme "istio.io/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ScopeConfigsGetter has a method to return a ScopeConfigInterface.
// A group's client should implement this interface.
type ScopeConfigsGetter interface {
	ScopeConfigs(namespace string) ScopeConfigInterface
}

// ScopeConfigInterface has methods to work with ScopeConfig resources.
type ScopeConfigInterface interface {
	Create(ctx context.Context, scopeConfig *v1beta1.ScopeConfig, opts v1.CreateOptions) (*v1beta1.ScopeConfig, error)
	Update(ctx context.Context, scopeConfig *v1beta1.ScopeConfig, opts v1.UpdateOptions) (*v1beta1.ScopeConfig, error)
	UpdateStatus(ctx context.Context, scopeConfig *v1beta1.ScopeConfig, opts v1.UpdateOptions) (*v1beta1.ScopeConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ScopeConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ScopeConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ScopeConfig, err error)
	Apply(ctx context.Context, scopeConfig *istiov1beta1.ScopeConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.ScopeConfig, err error)
	ApplyStatus(ctx context.Context, scopeConfig *istiov1beta1.ScopeConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.ScopeConfig, err error)
	ScopeConfigExpansion
}

// scopeConfigs implements ScopeConfigInterface
type scopeConfigs struct {
	client rest.Interface
	ns     string
}

// newScopeConfigs returns a ScopeConfigs
func newScopeConfigs(c *IstioV1beta1Client, namespace string) *scopeConfigs {
	return &scopeConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the scopeConfig, and returns the corresponding scopeConfig object, and an error if there is any.
func (c *scopeConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ScopeConfig, err error) {
	result = &v1beta1.ScopeConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ScopeConfigs that match those selectors.
func (c *scopeConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ScopeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ScopeConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scopeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested scopeConfigs.
func (c *scopeConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("scopeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a scopeConfig and creates it.  Returns the server's representation of the scopeConfig, and an error, if there is any.
func (c *scopeConfigs) Create(ctx context.Context, scopeConfig *v1beta1.ScopeConfig, opts v1.CreateOptions) (result *v1beta1.ScopeConfig, err error) {
	result = &v1beta1.ScopeConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("scopeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scopeConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a scopeConfig and updates it. Returns the server's representation of the scopeConfig, and an error, if there is any.
func (c *scopeConfigs) Update(ctx context.Context, scopeConfig *v1beta1.ScopeConfig, opts v1.UpdateOptions) (result *v1beta1.ScopeConfig, err error) {
	result = &v1beta1.ScopeConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(scopeConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scopeConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *scopeConfigs) UpdateStatus(ctx context.Context, scopeConfig *v1beta1.ScopeConfig, opts v1.UpdateOptions) (result *v1beta1.ScopeConfig, err error) {
	result = &v1beta1.ScopeConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(scopeConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scopeConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the scopeConfig and deletes it. Returns an error if one occurs.
func (c *scopeConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *scopeConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scopeconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched scopeConfig.
func (c *scopeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ScopeConfig, err error) {
	result = &v1beta1.ScopeConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied scopeConfig.
func (c *scopeConfigs) Apply(ctx context.Context, scopeConfig *istiov1beta1.ScopeConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.ScopeConfig, err error) {
	if scopeConfig == nil {
		return nil, fmt.Errorf("scopeConfig provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(scopeConfig)
	if err != nil {
		return nil, err
	}
	name := scopeConfig.Name
	if name == nil {
		return nil, fmt.Errorf("scopeConfig.Name must be provided to Apply")
	}
	result = &v1beta1.ScopeConfig{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *scopeConfigs) ApplyStatus(ctx context.Context, scopeConfig *istiov1beta1.ScopeConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.ScopeConfig, err error) {
	if scopeConfig == nil {
		return nil, fmt.Errorf("scopeConfig provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(scopeConfig)
	if err != nil {
		return nil, err
	}

	name := scopeConfig.Name
	if name == nil {
		return nil, fmt.Errorf("scopeConfig.Name must be provided to Apply")
	}

	result = &v1beta1.ScopeConfig{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("scopeconfigs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
