// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1beta1 "istio.io/client-go/pkg/apis/istio/v1beta1"
	istiov1beta1 "istio.io/client-go/pkg/applyconfiguration/istio/v1beta1"
	scheme "istio.io/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrafficLabelsGetter has a method to return a TrafficLabelInterface.
// A group's client should implement this interface.
type TrafficLabelsGetter interface {
	TrafficLabels(namespace string) TrafficLabelInterface
}

// TrafficLabelInterface has methods to work with TrafficLabel resources.
type TrafficLabelInterface interface {
	Create(ctx context.Context, trafficLabel *v1beta1.TrafficLabel, opts v1.CreateOptions) (*v1beta1.TrafficLabel, error)
	Update(ctx context.Context, trafficLabel *v1beta1.TrafficLabel, opts v1.UpdateOptions) (*v1beta1.TrafficLabel, error)
	UpdateStatus(ctx context.Context, trafficLabel *v1beta1.TrafficLabel, opts v1.UpdateOptions) (*v1beta1.TrafficLabel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.TrafficLabel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.TrafficLabelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.TrafficLabel, err error)
	Apply(ctx context.Context, trafficLabel *istiov1beta1.TrafficLabelApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.TrafficLabel, err error)
	ApplyStatus(ctx context.Context, trafficLabel *istiov1beta1.TrafficLabelApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.TrafficLabel, err error)
	TrafficLabelExpansion
}

// trafficLabels implements TrafficLabelInterface
type trafficLabels struct {
	client rest.Interface
	ns     string
}

// newTrafficLabels returns a TrafficLabels
func newTrafficLabels(c *IstioV1beta1Client, namespace string) *trafficLabels {
	return &trafficLabels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trafficLabel, and returns the corresponding trafficLabel object, and an error if there is any.
func (c *trafficLabels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.TrafficLabel, err error) {
	result = &v1beta1.TrafficLabel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrafficLabels that match those selectors.
func (c *trafficLabels) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.TrafficLabelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.TrafficLabelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trafficlabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trafficLabels.
func (c *trafficLabels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trafficlabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a trafficLabel and creates it.  Returns the server's representation of the trafficLabel, and an error, if there is any.
func (c *trafficLabels) Create(ctx context.Context, trafficLabel *v1beta1.TrafficLabel, opts v1.CreateOptions) (result *v1beta1.TrafficLabel, err error) {
	result = &v1beta1.TrafficLabel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trafficlabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficLabel).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a trafficLabel and updates it. Returns the server's representation of the trafficLabel, and an error, if there is any.
func (c *trafficLabels) Update(ctx context.Context, trafficLabel *v1beta1.TrafficLabel, opts v1.UpdateOptions) (result *v1beta1.TrafficLabel, err error) {
	result = &v1beta1.TrafficLabel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(trafficLabel.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficLabel).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *trafficLabels) UpdateStatus(ctx context.Context, trafficLabel *v1beta1.TrafficLabel, opts v1.UpdateOptions) (result *v1beta1.TrafficLabel, err error) {
	result = &v1beta1.TrafficLabel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(trafficLabel.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficLabel).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the trafficLabel and deletes it. Returns an error if one occurs.
func (c *trafficLabels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trafficLabels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trafficlabels").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched trafficLabel.
func (c *trafficLabels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.TrafficLabel, err error) {
	result = &v1beta1.TrafficLabel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied trafficLabel.
func (c *trafficLabels) Apply(ctx context.Context, trafficLabel *istiov1beta1.TrafficLabelApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.TrafficLabel, err error) {
	if trafficLabel == nil {
		return nil, fmt.Errorf("trafficLabel provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trafficLabel)
	if err != nil {
		return nil, err
	}
	name := trafficLabel.Name
	if name == nil {
		return nil, fmt.Errorf("trafficLabel.Name must be provided to Apply")
	}
	result = &v1beta1.TrafficLabel{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *trafficLabels) ApplyStatus(ctx context.Context, trafficLabel *istiov1beta1.TrafficLabelApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.TrafficLabel, err error) {
	if trafficLabel == nil {
		return nil, fmt.Errorf("trafficLabel provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trafficLabel)
	if err != nil {
		return nil, err
	}

	name := trafficLabel.Name
	if name == nil {
		return nil, fmt.Errorf("trafficLabel.Name must be provided to Apply")
	}

	result = &v1beta1.TrafficLabel{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trafficlabels").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
