// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMDecompressors implements ASMDecompressorInterface
type FakeASMDecompressors struct {
	Fake *FakeIstioV1
	ns   string
}

var asmdecompressorsResource = v1.SchemeGroupVersion.WithResource("asmdecompressors")

var asmdecompressorsKind = v1.SchemeGroupVersion.WithKind("ASMDecompressor")

// Get takes name of the aSMDecompressor, and returns the corresponding aSMDecompressor object, and an error if there is any.
func (c *FakeASMDecompressors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMDecompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmdecompressorsResource, c.ns, name), &v1.ASMDecompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMDecompressor), err
}

// List takes label and field selectors, and returns the list of ASMDecompressors that match those selectors.
func (c *FakeASMDecompressors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMDecompressorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmdecompressorsResource, asmdecompressorsKind, c.ns, opts), &v1.ASMDecompressorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMDecompressorList{ListMeta: obj.(*v1.ASMDecompressorList).ListMeta}
	for _, item := range obj.(*v1.ASMDecompressorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMDecompressors.
func (c *FakeASMDecompressors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmdecompressorsResource, c.ns, opts))

}

// Create takes the representation of a aSMDecompressor and creates it.  Returns the server's representation of the aSMDecompressor, and an error, if there is any.
func (c *FakeASMDecompressors) Create(ctx context.Context, aSMDecompressor *v1.ASMDecompressor, opts metav1.CreateOptions) (result *v1.ASMDecompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmdecompressorsResource, c.ns, aSMDecompressor), &v1.ASMDecompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMDecompressor), err
}

// Update takes the representation of a aSMDecompressor and updates it. Returns the server's representation of the aSMDecompressor, and an error, if there is any.
func (c *FakeASMDecompressors) Update(ctx context.Context, aSMDecompressor *v1.ASMDecompressor, opts metav1.UpdateOptions) (result *v1.ASMDecompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmdecompressorsResource, c.ns, aSMDecompressor), &v1.ASMDecompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMDecompressor), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMDecompressors) UpdateStatus(ctx context.Context, aSMDecompressor *v1.ASMDecompressor, opts metav1.UpdateOptions) (*v1.ASMDecompressor, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmdecompressorsResource, "status", c.ns, aSMDecompressor), &v1.ASMDecompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMDecompressor), err
}

// Delete takes name of the aSMDecompressor and deletes it. Returns an error if one occurs.
func (c *FakeASMDecompressors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmdecompressorsResource, c.ns, name, opts), &v1.ASMDecompressor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMDecompressors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmdecompressorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMDecompressorList{})
	return err
}

// Patch applies the patch and returns the patched aSMDecompressor.
func (c *FakeASMDecompressors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMDecompressor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmdecompressorsResource, c.ns, name, pt, data, subresources...), &v1.ASMDecompressor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMDecompressor), err
}
