// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMProxyConfigs implements ASMProxyConfigInterface
type FakeASMProxyConfigs struct {
	Fake *FakeIstioV1
	ns   string
}

var asmproxyconfigsResource = v1.SchemeGroupVersion.WithResource("asmproxyconfigs")

var asmproxyconfigsKind = v1.SchemeGroupVersion.WithKind("ASMProxyConfig")

// Get takes name of the aSMProxyConfig, and returns the corresponding aSMProxyConfig object, and an error if there is any.
func (c *FakeASMProxyConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMProxyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmproxyconfigsResource, c.ns, name), &v1.ASMProxyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMProxyConfig), err
}

// List takes label and field selectors, and returns the list of ASMProxyConfigs that match those selectors.
func (c *FakeASMProxyConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMProxyConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmproxyconfigsResource, asmproxyconfigsKind, c.ns, opts), &v1.ASMProxyConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMProxyConfigList{ListMeta: obj.(*v1.ASMProxyConfigList).ListMeta}
	for _, item := range obj.(*v1.ASMProxyConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMProxyConfigs.
func (c *FakeASMProxyConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmproxyconfigsResource, c.ns, opts))

}

// Create takes the representation of a aSMProxyConfig and creates it.  Returns the server's representation of the aSMProxyConfig, and an error, if there is any.
func (c *FakeASMProxyConfigs) Create(ctx context.Context, aSMProxyConfig *v1.ASMProxyConfig, opts metav1.CreateOptions) (result *v1.ASMProxyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmproxyconfigsResource, c.ns, aSMProxyConfig), &v1.ASMProxyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMProxyConfig), err
}

// Update takes the representation of a aSMProxyConfig and updates it. Returns the server's representation of the aSMProxyConfig, and an error, if there is any.
func (c *FakeASMProxyConfigs) Update(ctx context.Context, aSMProxyConfig *v1.ASMProxyConfig, opts metav1.UpdateOptions) (result *v1.ASMProxyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmproxyconfigsResource, c.ns, aSMProxyConfig), &v1.ASMProxyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMProxyConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMProxyConfigs) UpdateStatus(ctx context.Context, aSMProxyConfig *v1.ASMProxyConfig, opts metav1.UpdateOptions) (*v1.ASMProxyConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmproxyconfigsResource, "status", c.ns, aSMProxyConfig), &v1.ASMProxyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMProxyConfig), err
}

// Delete takes name of the aSMProxyConfig and deletes it. Returns an error if one occurs.
func (c *FakeASMProxyConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmproxyconfigsResource, c.ns, name, opts), &v1.ASMProxyConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMProxyConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmproxyconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMProxyConfigList{})
	return err
}

// Patch applies the patch and returns the patched aSMProxyConfig.
func (c *FakeASMProxyConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMProxyConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmproxyconfigsResource, c.ns, name, pt, data, subresources...), &v1.ASMProxyConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMProxyConfig), err
}
