// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMGlobalRateLimiters implements ASMGlobalRateLimiterInterface
type FakeASMGlobalRateLimiters struct {
	Fake *FakeIstioV1
	ns   string
}

var asmglobalratelimitersResource = v1.SchemeGroupVersion.WithResource("asmglobalratelimiters")

var asmglobalratelimitersKind = v1.SchemeGroupVersion.WithKind("ASMGlobalRateLimiter")

// Get takes name of the aSMGlobalRateLimiter, and returns the corresponding aSMGlobalRateLimiter object, and an error if there is any.
func (c *FakeASMGlobalRateLimiters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMGlobalRateLimiter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmglobalratelimitersResource, c.ns, name), &v1.ASMGlobalRateLimiter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGlobalRateLimiter), err
}

// List takes label and field selectors, and returns the list of ASMGlobalRateLimiters that match those selectors.
func (c *FakeASMGlobalRateLimiters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMGlobalRateLimiterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmglobalratelimitersResource, asmglobalratelimitersKind, c.ns, opts), &v1.ASMGlobalRateLimiterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMGlobalRateLimiterList{ListMeta: obj.(*v1.ASMGlobalRateLimiterList).ListMeta}
	for _, item := range obj.(*v1.ASMGlobalRateLimiterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMGlobalRateLimiters.
func (c *FakeASMGlobalRateLimiters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmglobalratelimitersResource, c.ns, opts))

}

// Create takes the representation of a aSMGlobalRateLimiter and creates it.  Returns the server's representation of the aSMGlobalRateLimiter, and an error, if there is any.
func (c *FakeASMGlobalRateLimiters) Create(ctx context.Context, aSMGlobalRateLimiter *v1.ASMGlobalRateLimiter, opts metav1.CreateOptions) (result *v1.ASMGlobalRateLimiter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmglobalratelimitersResource, c.ns, aSMGlobalRateLimiter), &v1.ASMGlobalRateLimiter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGlobalRateLimiter), err
}

// Update takes the representation of a aSMGlobalRateLimiter and updates it. Returns the server's representation of the aSMGlobalRateLimiter, and an error, if there is any.
func (c *FakeASMGlobalRateLimiters) Update(ctx context.Context, aSMGlobalRateLimiter *v1.ASMGlobalRateLimiter, opts metav1.UpdateOptions) (result *v1.ASMGlobalRateLimiter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmglobalratelimitersResource, c.ns, aSMGlobalRateLimiter), &v1.ASMGlobalRateLimiter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGlobalRateLimiter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMGlobalRateLimiters) UpdateStatus(ctx context.Context, aSMGlobalRateLimiter *v1.ASMGlobalRateLimiter, opts metav1.UpdateOptions) (*v1.ASMGlobalRateLimiter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmglobalratelimitersResource, "status", c.ns, aSMGlobalRateLimiter), &v1.ASMGlobalRateLimiter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGlobalRateLimiter), err
}

// Delete takes name of the aSMGlobalRateLimiter and deletes it. Returns an error if one occurs.
func (c *FakeASMGlobalRateLimiters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmglobalratelimitersResource, c.ns, name, opts), &v1.ASMGlobalRateLimiter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMGlobalRateLimiters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmglobalratelimitersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMGlobalRateLimiterList{})
	return err
}

// Patch applies the patch and returns the patched aSMGlobalRateLimiter.
func (c *FakeASMGlobalRateLimiters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMGlobalRateLimiter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmglobalratelimitersResource, c.ns, name, pt, data, subresources...), &v1.ASMGlobalRateLimiter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMGlobalRateLimiter), err
}
