// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMSwimLanes implements ASMSwimLaneInterface
type FakeASMSwimLanes struct {
	Fake *FakeIstioV1
}

var asmswimlanesResource = v1.SchemeGroupVersion.WithResource("asmswimlanes")

var asmswimlanesKind = v1.SchemeGroupVersion.WithKind("ASMSwimLane")

// Get takes name of the aSMSwimLane, and returns the corresponding aSMSwimLane object, and an error if there is any.
func (c *FakeASMSwimLanes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMSwimLane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(asmswimlanesResource, name), &v1.ASMSwimLane{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSwimLane), err
}

// List takes label and field selectors, and returns the list of ASMSwimLanes that match those selectors.
func (c *FakeASMSwimLanes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMSwimLaneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(asmswimlanesResource, asmswimlanesKind, opts), &v1.ASMSwimLaneList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMSwimLaneList{ListMeta: obj.(*v1.ASMSwimLaneList).ListMeta}
	for _, item := range obj.(*v1.ASMSwimLaneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMSwimLanes.
func (c *FakeASMSwimLanes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(asmswimlanesResource, opts))
}

// Create takes the representation of a aSMSwimLane and creates it.  Returns the server's representation of the aSMSwimLane, and an error, if there is any.
func (c *FakeASMSwimLanes) Create(ctx context.Context, aSMSwimLane *v1.ASMSwimLane, opts metav1.CreateOptions) (result *v1.ASMSwimLane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(asmswimlanesResource, aSMSwimLane), &v1.ASMSwimLane{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSwimLane), err
}

// Update takes the representation of a aSMSwimLane and updates it. Returns the server's representation of the aSMSwimLane, and an error, if there is any.
func (c *FakeASMSwimLanes) Update(ctx context.Context, aSMSwimLane *v1.ASMSwimLane, opts metav1.UpdateOptions) (result *v1.ASMSwimLane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(asmswimlanesResource, aSMSwimLane), &v1.ASMSwimLane{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSwimLane), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMSwimLanes) UpdateStatus(ctx context.Context, aSMSwimLane *v1.ASMSwimLane, opts metav1.UpdateOptions) (*v1.ASMSwimLane, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(asmswimlanesResource, "status", aSMSwimLane), &v1.ASMSwimLane{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSwimLane), err
}

// Delete takes name of the aSMSwimLane and deletes it. Returns an error if one occurs.
func (c *FakeASMSwimLanes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(asmswimlanesResource, name, opts), &v1.ASMSwimLane{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMSwimLanes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(asmswimlanesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMSwimLaneList{})
	return err
}

// Patch applies the patch and returns the patched aSMSwimLane.
func (c *FakeASMSwimLanes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMSwimLane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(asmswimlanesResource, name, pt, data, subresources...), &v1.ASMSwimLane{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSwimLane), err
}
