// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvoyFilterTemplates implements EnvoyFilterTemplateInterface
type FakeEnvoyFilterTemplates struct {
	Fake *FakeIstioV1
	ns   string
}

var envoyfiltertemplatesResource = v1.SchemeGroupVersion.WithResource("envoyfiltertemplates")

var envoyfiltertemplatesKind = v1.SchemeGroupVersion.WithKind("EnvoyFilterTemplate")

// Get takes name of the envoyFilterTemplate, and returns the corresponding envoyFilterTemplate object, and an error if there is any.
func (c *FakeEnvoyFilterTemplates) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EnvoyFilterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(envoyfiltertemplatesResource, c.ns, name), &v1.EnvoyFilterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplate), err
}

// List takes label and field selectors, and returns the list of EnvoyFilterTemplates that match those selectors.
func (c *FakeEnvoyFilterTemplates) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EnvoyFilterTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(envoyfiltertemplatesResource, envoyfiltertemplatesKind, c.ns, opts), &v1.EnvoyFilterTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EnvoyFilterTemplateList{ListMeta: obj.(*v1.EnvoyFilterTemplateList).ListMeta}
	for _, item := range obj.(*v1.EnvoyFilterTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested envoyFilterTemplates.
func (c *FakeEnvoyFilterTemplates) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(envoyfiltertemplatesResource, c.ns, opts))

}

// Create takes the representation of a envoyFilterTemplate and creates it.  Returns the server's representation of the envoyFilterTemplate, and an error, if there is any.
func (c *FakeEnvoyFilterTemplates) Create(ctx context.Context, envoyFilterTemplate *v1.EnvoyFilterTemplate, opts metav1.CreateOptions) (result *v1.EnvoyFilterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(envoyfiltertemplatesResource, c.ns, envoyFilterTemplate), &v1.EnvoyFilterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplate), err
}

// Update takes the representation of a envoyFilterTemplate and updates it. Returns the server's representation of the envoyFilterTemplate, and an error, if there is any.
func (c *FakeEnvoyFilterTemplates) Update(ctx context.Context, envoyFilterTemplate *v1.EnvoyFilterTemplate, opts metav1.UpdateOptions) (result *v1.EnvoyFilterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(envoyfiltertemplatesResource, c.ns, envoyFilterTemplate), &v1.EnvoyFilterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnvoyFilterTemplates) UpdateStatus(ctx context.Context, envoyFilterTemplate *v1.EnvoyFilterTemplate, opts metav1.UpdateOptions) (*v1.EnvoyFilterTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(envoyfiltertemplatesResource, "status", c.ns, envoyFilterTemplate), &v1.EnvoyFilterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplate), err
}

// Delete takes name of the envoyFilterTemplate and deletes it. Returns an error if one occurs.
func (c *FakeEnvoyFilterTemplates) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(envoyfiltertemplatesResource, c.ns, name, opts), &v1.EnvoyFilterTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvoyFilterTemplates) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(envoyfiltertemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EnvoyFilterTemplateList{})
	return err
}

// Patch applies the patch and returns the patched envoyFilterTemplate.
func (c *FakeEnvoyFilterTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EnvoyFilterTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(envoyfiltertemplatesResource, c.ns, name, pt, data, subresources...), &v1.EnvoyFilterTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplate), err
}
