// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMSecurityPolicies implements ASMSecurityPolicyInterface
type FakeASMSecurityPolicies struct {
	Fake *FakeIstioV1
}

var asmsecuritypoliciesResource = v1.SchemeGroupVersion.WithResource("asmsecuritypolicies")

var asmsecuritypoliciesKind = v1.SchemeGroupVersion.WithKind("ASMSecurityPolicy")

// Get takes name of the aSMSecurityPolicy, and returns the corresponding aSMSecurityPolicy object, and an error if there is any.
func (c *FakeASMSecurityPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(asmsecuritypoliciesResource, name), &v1.ASMSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSecurityPolicy), err
}

// List takes label and field selectors, and returns the list of ASMSecurityPolicies that match those selectors.
func (c *FakeASMSecurityPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMSecurityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(asmsecuritypoliciesResource, asmsecuritypoliciesKind, opts), &v1.ASMSecurityPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMSecurityPolicyList{ListMeta: obj.(*v1.ASMSecurityPolicyList).ListMeta}
	for _, item := range obj.(*v1.ASMSecurityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMSecurityPolicies.
func (c *FakeASMSecurityPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(asmsecuritypoliciesResource, opts))
}

// Create takes the representation of a aSMSecurityPolicy and creates it.  Returns the server's representation of the aSMSecurityPolicy, and an error, if there is any.
func (c *FakeASMSecurityPolicies) Create(ctx context.Context, aSMSecurityPolicy *v1.ASMSecurityPolicy, opts metav1.CreateOptions) (result *v1.ASMSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(asmsecuritypoliciesResource, aSMSecurityPolicy), &v1.ASMSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSecurityPolicy), err
}

// Update takes the representation of a aSMSecurityPolicy and updates it. Returns the server's representation of the aSMSecurityPolicy, and an error, if there is any.
func (c *FakeASMSecurityPolicies) Update(ctx context.Context, aSMSecurityPolicy *v1.ASMSecurityPolicy, opts metav1.UpdateOptions) (result *v1.ASMSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(asmsecuritypoliciesResource, aSMSecurityPolicy), &v1.ASMSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSecurityPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMSecurityPolicies) UpdateStatus(ctx context.Context, aSMSecurityPolicy *v1.ASMSecurityPolicy, opts metav1.UpdateOptions) (*v1.ASMSecurityPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(asmsecuritypoliciesResource, "status", aSMSecurityPolicy), &v1.ASMSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSecurityPolicy), err
}

// Delete takes name of the aSMSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeASMSecurityPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(asmsecuritypoliciesResource, name, opts), &v1.ASMSecurityPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMSecurityPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(asmsecuritypoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMSecurityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched aSMSecurityPolicy.
func (c *FakeASMSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(asmsecuritypoliciesResource, name, pt, data, subresources...), &v1.ASMSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMSecurityPolicy), err
}
