// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMHashTaggings implements ASMHashTaggingInterface
type FakeASMHashTaggings struct {
	Fake *FakeIstioV1
	ns   string
}

var asmhashtaggingsResource = v1.SchemeGroupVersion.WithResource("asmhashtaggings")

var asmhashtaggingsKind = v1.SchemeGroupVersion.WithKind("ASMHashTagging")

// Get takes name of the aSMHashTagging, and returns the corresponding aSMHashTagging object, and an error if there is any.
func (c *FakeASMHashTaggings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMHashTagging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmhashtaggingsResource, c.ns, name), &v1.ASMHashTagging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMHashTagging), err
}

// List takes label and field selectors, and returns the list of ASMHashTaggings that match those selectors.
func (c *FakeASMHashTaggings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMHashTaggingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmhashtaggingsResource, asmhashtaggingsKind, c.ns, opts), &v1.ASMHashTaggingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMHashTaggingList{ListMeta: obj.(*v1.ASMHashTaggingList).ListMeta}
	for _, item := range obj.(*v1.ASMHashTaggingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMHashTaggings.
func (c *FakeASMHashTaggings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmhashtaggingsResource, c.ns, opts))

}

// Create takes the representation of a aSMHashTagging and creates it.  Returns the server's representation of the aSMHashTagging, and an error, if there is any.
func (c *FakeASMHashTaggings) Create(ctx context.Context, aSMHashTagging *v1.ASMHashTagging, opts metav1.CreateOptions) (result *v1.ASMHashTagging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmhashtaggingsResource, c.ns, aSMHashTagging), &v1.ASMHashTagging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMHashTagging), err
}

// Update takes the representation of a aSMHashTagging and updates it. Returns the server's representation of the aSMHashTagging, and an error, if there is any.
func (c *FakeASMHashTaggings) Update(ctx context.Context, aSMHashTagging *v1.ASMHashTagging, opts metav1.UpdateOptions) (result *v1.ASMHashTagging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmhashtaggingsResource, c.ns, aSMHashTagging), &v1.ASMHashTagging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMHashTagging), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMHashTaggings) UpdateStatus(ctx context.Context, aSMHashTagging *v1.ASMHashTagging, opts metav1.UpdateOptions) (*v1.ASMHashTagging, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmhashtaggingsResource, "status", c.ns, aSMHashTagging), &v1.ASMHashTagging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMHashTagging), err
}

// Delete takes name of the aSMHashTagging and deletes it. Returns an error if one occurs.
func (c *FakeASMHashTaggings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmhashtaggingsResource, c.ns, name, opts), &v1.ASMHashTagging{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMHashTaggings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmhashtaggingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMHashTaggingList{})
	return err
}

// Patch applies the patch and returns the patched aSMHashTagging.
func (c *FakeASMHashTaggings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMHashTagging, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmhashtaggingsResource, c.ns, name, pt, data, subresources...), &v1.ASMHashTagging{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMHashTagging), err
}
