// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMPacketInspectors implements ASMPacketInspectorInterface
type FakeASMPacketInspectors struct {
	Fake *FakeIstioV1
}

var asmpacketinspectorsResource = v1.SchemeGroupVersion.WithResource("asmpacketinspectors")

var asmpacketinspectorsKind = v1.SchemeGroupVersion.WithKind("ASMPacketInspector")

// Get takes name of the aSMPacketInspector, and returns the corresponding aSMPacketInspector object, and an error if there is any.
func (c *FakeASMPacketInspectors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMPacketInspector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(asmpacketinspectorsResource, name), &v1.ASMPacketInspector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMPacketInspector), err
}

// List takes label and field selectors, and returns the list of ASMPacketInspectors that match those selectors.
func (c *FakeASMPacketInspectors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMPacketInspectorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(asmpacketinspectorsResource, asmpacketinspectorsKind, opts), &v1.ASMPacketInspectorList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMPacketInspectorList{ListMeta: obj.(*v1.ASMPacketInspectorList).ListMeta}
	for _, item := range obj.(*v1.ASMPacketInspectorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMPacketInspectors.
func (c *FakeASMPacketInspectors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(asmpacketinspectorsResource, opts))
}

// Create takes the representation of a aSMPacketInspector and creates it.  Returns the server's representation of the aSMPacketInspector, and an error, if there is any.
func (c *FakeASMPacketInspectors) Create(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.CreateOptions) (result *v1.ASMPacketInspector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(asmpacketinspectorsResource, aSMPacketInspector), &v1.ASMPacketInspector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMPacketInspector), err
}

// Update takes the representation of a aSMPacketInspector and updates it. Returns the server's representation of the aSMPacketInspector, and an error, if there is any.
func (c *FakeASMPacketInspectors) Update(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.UpdateOptions) (result *v1.ASMPacketInspector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(asmpacketinspectorsResource, aSMPacketInspector), &v1.ASMPacketInspector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMPacketInspector), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMPacketInspectors) UpdateStatus(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.UpdateOptions) (*v1.ASMPacketInspector, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(asmpacketinspectorsResource, "status", aSMPacketInspector), &v1.ASMPacketInspector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMPacketInspector), err
}

// Delete takes name of the aSMPacketInspector and deletes it. Returns an error if one occurs.
func (c *FakeASMPacketInspectors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(asmpacketinspectorsResource, name, opts), &v1.ASMPacketInspector{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMPacketInspectors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(asmpacketinspectorsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMPacketInspectorList{})
	return err
}

// Patch applies the patch and returns the patched aSMPacketInspector.
func (c *FakeASMPacketInspectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMPacketInspector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(asmpacketinspectorsResource, name, pt, data, subresources...), &v1.ASMPacketInspector{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMPacketInspector), err
}
