// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvoyFilterTemplateBindings implements EnvoyFilterTemplateBindingInterface
type FakeEnvoyFilterTemplateBindings struct {
	Fake *FakeIstioV1
	ns   string
}

var envoyfiltertemplatebindingsResource = v1.SchemeGroupVersion.WithResource("envoyfiltertemplatebindings")

var envoyfiltertemplatebindingsKind = v1.SchemeGroupVersion.WithKind("EnvoyFilterTemplateBinding")

// Get takes name of the envoyFilterTemplateBinding, and returns the corresponding envoyFilterTemplateBinding object, and an error if there is any.
func (c *FakeEnvoyFilterTemplateBindings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EnvoyFilterTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(envoyfiltertemplatebindingsResource, c.ns, name), &v1.EnvoyFilterTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplateBinding), err
}

// List takes label and field selectors, and returns the list of EnvoyFilterTemplateBindings that match those selectors.
func (c *FakeEnvoyFilterTemplateBindings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EnvoyFilterTemplateBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(envoyfiltertemplatebindingsResource, envoyfiltertemplatebindingsKind, c.ns, opts), &v1.EnvoyFilterTemplateBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EnvoyFilterTemplateBindingList{ListMeta: obj.(*v1.EnvoyFilterTemplateBindingList).ListMeta}
	for _, item := range obj.(*v1.EnvoyFilterTemplateBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested envoyFilterTemplateBindings.
func (c *FakeEnvoyFilterTemplateBindings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(envoyfiltertemplatebindingsResource, c.ns, opts))

}

// Create takes the representation of a envoyFilterTemplateBinding and creates it.  Returns the server's representation of the envoyFilterTemplateBinding, and an error, if there is any.
func (c *FakeEnvoyFilterTemplateBindings) Create(ctx context.Context, envoyFilterTemplateBinding *v1.EnvoyFilterTemplateBinding, opts metav1.CreateOptions) (result *v1.EnvoyFilterTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(envoyfiltertemplatebindingsResource, c.ns, envoyFilterTemplateBinding), &v1.EnvoyFilterTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplateBinding), err
}

// Update takes the representation of a envoyFilterTemplateBinding and updates it. Returns the server's representation of the envoyFilterTemplateBinding, and an error, if there is any.
func (c *FakeEnvoyFilterTemplateBindings) Update(ctx context.Context, envoyFilterTemplateBinding *v1.EnvoyFilterTemplateBinding, opts metav1.UpdateOptions) (result *v1.EnvoyFilterTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(envoyfiltertemplatebindingsResource, c.ns, envoyFilterTemplateBinding), &v1.EnvoyFilterTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplateBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnvoyFilterTemplateBindings) UpdateStatus(ctx context.Context, envoyFilterTemplateBinding *v1.EnvoyFilterTemplateBinding, opts metav1.UpdateOptions) (*v1.EnvoyFilterTemplateBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(envoyfiltertemplatebindingsResource, "status", c.ns, envoyFilterTemplateBinding), &v1.EnvoyFilterTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplateBinding), err
}

// Delete takes name of the envoyFilterTemplateBinding and deletes it. Returns an error if one occurs.
func (c *FakeEnvoyFilterTemplateBindings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(envoyfiltertemplatebindingsResource, c.ns, name, opts), &v1.EnvoyFilterTemplateBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvoyFilterTemplateBindings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(envoyfiltertemplatebindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EnvoyFilterTemplateBindingList{})
	return err
}

// Patch applies the patch and returns the patched envoyFilterTemplateBinding.
func (c *FakeEnvoyFilterTemplateBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EnvoyFilterTemplateBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(envoyfiltertemplatebindingsResource, c.ns, name, pt, data, subresources...), &v1.EnvoyFilterTemplateBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EnvoyFilterTemplateBinding), err
}
