// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMMigrateFromIstios implements ASMMigrateFromIstioInterface
type FakeASMMigrateFromIstios struct {
	Fake *FakeIstioV1
}

var asmmigratefromistiosResource = v1.SchemeGroupVersion.WithResource("asmmigratefromistios")

var asmmigratefromistiosKind = v1.SchemeGroupVersion.WithKind("ASMMigrateFromIstio")

// Get takes name of the aSMMigrateFromIstio, and returns the corresponding aSMMigrateFromIstio object, and an error if there is any.
func (c *FakeASMMigrateFromIstios) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMMigrateFromIstio, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(asmmigratefromistiosResource, name), &v1.ASMMigrateFromIstio{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMMigrateFromIstio), err
}

// List takes label and field selectors, and returns the list of ASMMigrateFromIstios that match those selectors.
func (c *FakeASMMigrateFromIstios) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMMigrateFromIstioList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(asmmigratefromistiosResource, asmmigratefromistiosKind, opts), &v1.ASMMigrateFromIstioList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMMigrateFromIstioList{ListMeta: obj.(*v1.ASMMigrateFromIstioList).ListMeta}
	for _, item := range obj.(*v1.ASMMigrateFromIstioList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMMigrateFromIstios.
func (c *FakeASMMigrateFromIstios) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(asmmigratefromistiosResource, opts))
}

// Create takes the representation of a aSMMigrateFromIstio and creates it.  Returns the server's representation of the aSMMigrateFromIstio, and an error, if there is any.
func (c *FakeASMMigrateFromIstios) Create(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.CreateOptions) (result *v1.ASMMigrateFromIstio, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(asmmigratefromistiosResource, aSMMigrateFromIstio), &v1.ASMMigrateFromIstio{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMMigrateFromIstio), err
}

// Update takes the representation of a aSMMigrateFromIstio and updates it. Returns the server's representation of the aSMMigrateFromIstio, and an error, if there is any.
func (c *FakeASMMigrateFromIstios) Update(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.UpdateOptions) (result *v1.ASMMigrateFromIstio, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(asmmigratefromistiosResource, aSMMigrateFromIstio), &v1.ASMMigrateFromIstio{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMMigrateFromIstio), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMMigrateFromIstios) UpdateStatus(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.UpdateOptions) (*v1.ASMMigrateFromIstio, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(asmmigratefromistiosResource, "status", aSMMigrateFromIstio), &v1.ASMMigrateFromIstio{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMMigrateFromIstio), err
}

// Delete takes name of the aSMMigrateFromIstio and deletes it. Returns an error if one occurs.
func (c *FakeASMMigrateFromIstios) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(asmmigratefromistiosResource, name, opts), &v1.ASMMigrateFromIstio{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMMigrateFromIstios) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(asmmigratefromistiosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMMigrateFromIstioList{})
	return err
}

// Patch applies the patch and returns the patched aSMMigrateFromIstio.
func (c *FakeASMMigrateFromIstios) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMMigrateFromIstio, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(asmmigratefromistiosResource, name, pt, data, subresources...), &v1.ASMMigrateFromIstio{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMMigrateFromIstio), err
}
