// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMCredentials implements ASMCredentialInterface
type FakeASMCredentials struct {
	Fake *FakeIstioV1
	ns   string
}

var asmcredentialsResource = v1.SchemeGroupVersion.WithResource("asmcredentials")

var asmcredentialsKind = v1.SchemeGroupVersion.WithKind("ASMCredential")

// Get takes name of the aSMCredential, and returns the corresponding aSMCredential object, and an error if there is any.
func (c *FakeASMCredentials) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmcredentialsResource, c.ns, name), &v1.ASMCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCredential), err
}

// List takes label and field selectors, and returns the list of ASMCredentials that match those selectors.
func (c *FakeASMCredentials) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMCredentialList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmcredentialsResource, asmcredentialsKind, c.ns, opts), &v1.ASMCredentialList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMCredentialList{ListMeta: obj.(*v1.ASMCredentialList).ListMeta}
	for _, item := range obj.(*v1.ASMCredentialList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMCredentials.
func (c *FakeASMCredentials) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmcredentialsResource, c.ns, opts))

}

// Create takes the representation of a aSMCredential and creates it.  Returns the server's representation of the aSMCredential, and an error, if there is any.
func (c *FakeASMCredentials) Create(ctx context.Context, aSMCredential *v1.ASMCredential, opts metav1.CreateOptions) (result *v1.ASMCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmcredentialsResource, c.ns, aSMCredential), &v1.ASMCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCredential), err
}

// Update takes the representation of a aSMCredential and updates it. Returns the server's representation of the aSMCredential, and an error, if there is any.
func (c *FakeASMCredentials) Update(ctx context.Context, aSMCredential *v1.ASMCredential, opts metav1.UpdateOptions) (result *v1.ASMCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmcredentialsResource, c.ns, aSMCredential), &v1.ASMCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCredential), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMCredentials) UpdateStatus(ctx context.Context, aSMCredential *v1.ASMCredential, opts metav1.UpdateOptions) (*v1.ASMCredential, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmcredentialsResource, "status", c.ns, aSMCredential), &v1.ASMCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCredential), err
}

// Delete takes name of the aSMCredential and deletes it. Returns an error if one occurs.
func (c *FakeASMCredentials) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmcredentialsResource, c.ns, name, opts), &v1.ASMCredential{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMCredentials) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmcredentialsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMCredentialList{})
	return err
}

// Patch applies the patch and returns the patched aSMCredential.
func (c *FakeASMCredentials) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmcredentialsResource, c.ns, name, pt, data, subresources...), &v1.ASMCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCredential), err
}
