// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "istio.io/client-go/pkg/apis/istio/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ScopeConfigLister helps list ScopeConfigs.
// All objects returned here must be treated as read-only.
type ScopeConfigLister interface {
	// List lists all ScopeConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ScopeConfig, err error)
	// ScopeConfigs returns an object that can list and get ScopeConfigs.
	ScopeConfigs(namespace string) ScopeConfigNamespaceLister
	ScopeConfigListerExpansion
}

// scopeConfigLister implements the ScopeConfigLister interface.
type scopeConfigLister struct {
	indexer cache.Indexer
}

// NewScopeConfigLister returns a new ScopeConfigLister.
func NewScopeConfigLister(indexer cache.Indexer) ScopeConfigLister {
	return &scopeConfigLister{indexer: indexer}
}

// List lists all ScopeConfigs in the indexer.
func (s *scopeConfigLister) List(selector labels.Selector) (ret []*v1beta1.ScopeConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ScopeConfig))
	})
	return ret, err
}

// ScopeConfigs returns an object that can list and get ScopeConfigs.
func (s *scopeConfigLister) ScopeConfigs(namespace string) ScopeConfigNamespaceLister {
	return scopeConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ScopeConfigNamespaceLister helps list and get ScopeConfigs.
// All objects returned here must be treated as read-only.
type ScopeConfigNamespaceLister interface {
	// List lists all ScopeConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ScopeConfig, err error)
	// Get retrieves the ScopeConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ScopeConfig, error)
	ScopeConfigNamespaceListerExpansion
}

// scopeConfigNamespaceLister implements the ScopeConfigNamespaceLister
// interface.
type scopeConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ScopeConfigs in the indexer for a given namespace.
func (s scopeConfigNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.ScopeConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ScopeConfig))
	})
	return ret, err
}

// Get retrieves the ScopeConfig from the indexer for a given namespace and name.
func (s scopeConfigNamespaceLister) Get(name string) (*v1beta1.ScopeConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("scopeconfig"), name)
	}
	return obj.(*v1beta1.ScopeConfig), nil
}
