// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "istio.io/client-go/pkg/apis/istio/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TrafficLabelLister helps list TrafficLabels.
// All objects returned here must be treated as read-only.
type TrafficLabelLister interface {
	// List lists all TrafficLabels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.TrafficLabel, err error)
	// TrafficLabels returns an object that can list and get TrafficLabels.
	TrafficLabels(namespace string) TrafficLabelNamespaceLister
	TrafficLabelListerExpansion
}

// trafficLabelLister implements the TrafficLabelLister interface.
type trafficLabelLister struct {
	indexer cache.Indexer
}

// NewTrafficLabelLister returns a new TrafficLabelLister.
func NewTrafficLabelLister(indexer cache.Indexer) TrafficLabelLister {
	return &trafficLabelLister{indexer: indexer}
}

// List lists all TrafficLabels in the indexer.
func (s *trafficLabelLister) List(selector labels.Selector) (ret []*v1beta1.TrafficLabel, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.TrafficLabel))
	})
	return ret, err
}

// TrafficLabels returns an object that can list and get TrafficLabels.
func (s *trafficLabelLister) TrafficLabels(namespace string) TrafficLabelNamespaceLister {
	return trafficLabelNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TrafficLabelNamespaceLister helps list and get TrafficLabels.
// All objects returned here must be treated as read-only.
type TrafficLabelNamespaceLister interface {
	// List lists all TrafficLabels in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.TrafficLabel, err error)
	// Get retrieves the TrafficLabel from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.TrafficLabel, error)
	TrafficLabelNamespaceListerExpansion
}

// trafficLabelNamespaceLister implements the TrafficLabelNamespaceLister
// interface.
type trafficLabelNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TrafficLabels in the indexer for a given namespace.
func (s trafficLabelNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.TrafficLabel, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.TrafficLabel))
	})
	return ret, err
}

// Get retrieves the TrafficLabel from the indexer for a given namespace and name.
func (s trafficLabelNamespaceLister) Get(name string) (*v1beta1.TrafficLabel, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("trafficlabel"), name)
	}
	return obj.(*v1beta1.TrafficLabel), nil
}
