// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/ampere/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AverageLatencySchedulingPolicyLister helps list AverageLatencySchedulingPolicies.
// All objects returned here must be treated as read-only.
type AverageLatencySchedulingPolicyLister interface {
	// List lists all AverageLatencySchedulingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AverageLatencySchedulingPolicy, err error)
	// AverageLatencySchedulingPolicies returns an object that can list and get AverageLatencySchedulingPolicies.
	AverageLatencySchedulingPolicies(namespace string) AverageLatencySchedulingPolicyNamespaceLister
	AverageLatencySchedulingPolicyListerExpansion
}

// averageLatencySchedulingPolicyLister implements the AverageLatencySchedulingPolicyLister interface.
type averageLatencySchedulingPolicyLister struct {
	indexer cache.Indexer
}

// NewAverageLatencySchedulingPolicyLister returns a new AverageLatencySchedulingPolicyLister.
func NewAverageLatencySchedulingPolicyLister(indexer cache.Indexer) AverageLatencySchedulingPolicyLister {
	return &averageLatencySchedulingPolicyLister{indexer: indexer}
}

// List lists all AverageLatencySchedulingPolicies in the indexer.
func (s *averageLatencySchedulingPolicyLister) List(selector labels.Selector) (ret []*v1.AverageLatencySchedulingPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AverageLatencySchedulingPolicy))
	})
	return ret, err
}

// AverageLatencySchedulingPolicies returns an object that can list and get AverageLatencySchedulingPolicies.
func (s *averageLatencySchedulingPolicyLister) AverageLatencySchedulingPolicies(namespace string) AverageLatencySchedulingPolicyNamespaceLister {
	return averageLatencySchedulingPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AverageLatencySchedulingPolicyNamespaceLister helps list and get AverageLatencySchedulingPolicies.
// All objects returned here must be treated as read-only.
type AverageLatencySchedulingPolicyNamespaceLister interface {
	// List lists all AverageLatencySchedulingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AverageLatencySchedulingPolicy, err error)
	// Get retrieves the AverageLatencySchedulingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.AverageLatencySchedulingPolicy, error)
	AverageLatencySchedulingPolicyNamespaceListerExpansion
}

// averageLatencySchedulingPolicyNamespaceLister implements the AverageLatencySchedulingPolicyNamespaceLister
// interface.
type averageLatencySchedulingPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AverageLatencySchedulingPolicies in the indexer for a given namespace.
func (s averageLatencySchedulingPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.AverageLatencySchedulingPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AverageLatencySchedulingPolicy))
	})
	return ret, err
}

// Get retrieves the AverageLatencySchedulingPolicy from the indexer for a given namespace and name.
func (s averageLatencySchedulingPolicyNamespaceLister) Get(name string) (*v1.AverageLatencySchedulingPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("averagelatencyschedulingpolicy"), name)
	}
	return obj.(*v1.AverageLatencySchedulingPolicy), nil
}
