// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/ampere/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ConcurrencyLimitingPolicyLister helps list ConcurrencyLimitingPolicies.
// All objects returned here must be treated as read-only.
type ConcurrencyLimitingPolicyLister interface {
	// List lists all ConcurrencyLimitingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ConcurrencyLimitingPolicy, err error)
	// ConcurrencyLimitingPolicies returns an object that can list and get ConcurrencyLimitingPolicies.
	ConcurrencyLimitingPolicies(namespace string) ConcurrencyLimitingPolicyNamespaceLister
	ConcurrencyLimitingPolicyListerExpansion
}

// concurrencyLimitingPolicyLister implements the ConcurrencyLimitingPolicyLister interface.
type concurrencyLimitingPolicyLister struct {
	indexer cache.Indexer
}

// NewConcurrencyLimitingPolicyLister returns a new ConcurrencyLimitingPolicyLister.
func NewConcurrencyLimitingPolicyLister(indexer cache.Indexer) ConcurrencyLimitingPolicyLister {
	return &concurrencyLimitingPolicyLister{indexer: indexer}
}

// List lists all ConcurrencyLimitingPolicies in the indexer.
func (s *concurrencyLimitingPolicyLister) List(selector labels.Selector) (ret []*v1.ConcurrencyLimitingPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ConcurrencyLimitingPolicy))
	})
	return ret, err
}

// ConcurrencyLimitingPolicies returns an object that can list and get ConcurrencyLimitingPolicies.
func (s *concurrencyLimitingPolicyLister) ConcurrencyLimitingPolicies(namespace string) ConcurrencyLimitingPolicyNamespaceLister {
	return concurrencyLimitingPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ConcurrencyLimitingPolicyNamespaceLister helps list and get ConcurrencyLimitingPolicies.
// All objects returned here must be treated as read-only.
type ConcurrencyLimitingPolicyNamespaceLister interface {
	// List lists all ConcurrencyLimitingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ConcurrencyLimitingPolicy, err error)
	// Get retrieves the ConcurrencyLimitingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ConcurrencyLimitingPolicy, error)
	ConcurrencyLimitingPolicyNamespaceListerExpansion
}

// concurrencyLimitingPolicyNamespaceLister implements the ConcurrencyLimitingPolicyNamespaceLister
// interface.
type concurrencyLimitingPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ConcurrencyLimitingPolicies in the indexer for a given namespace.
func (s concurrencyLimitingPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.ConcurrencyLimitingPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ConcurrencyLimitingPolicy))
	})
	return ret, err
}

// Get retrieves the ConcurrencyLimitingPolicy from the indexer for a given namespace and name.
func (s concurrencyLimitingPolicyNamespaceLister) Get(name string) (*v1.ConcurrencyLimitingPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("concurrencylimitingpolicy"), name)
	}
	return obj.(*v1.ConcurrencyLimitingPolicy), nil
}
