// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/ampere/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ConcurrencySchedulingPolicyLister helps list ConcurrencySchedulingPolicies.
// All objects returned here must be treated as read-only.
type ConcurrencySchedulingPolicyLister interface {
	// List lists all ConcurrencySchedulingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ConcurrencySchedulingPolicy, err error)
	// ConcurrencySchedulingPolicies returns an object that can list and get ConcurrencySchedulingPolicies.
	ConcurrencySchedulingPolicies(namespace string) ConcurrencySchedulingPolicyNamespaceLister
	ConcurrencySchedulingPolicyListerExpansion
}

// concurrencySchedulingPolicyLister implements the ConcurrencySchedulingPolicyLister interface.
type concurrencySchedulingPolicyLister struct {
	indexer cache.Indexer
}

// NewConcurrencySchedulingPolicyLister returns a new ConcurrencySchedulingPolicyLister.
func NewConcurrencySchedulingPolicyLister(indexer cache.Indexer) ConcurrencySchedulingPolicyLister {
	return &concurrencySchedulingPolicyLister{indexer: indexer}
}

// List lists all ConcurrencySchedulingPolicies in the indexer.
func (s *concurrencySchedulingPolicyLister) List(selector labels.Selector) (ret []*v1.ConcurrencySchedulingPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ConcurrencySchedulingPolicy))
	})
	return ret, err
}

// ConcurrencySchedulingPolicies returns an object that can list and get ConcurrencySchedulingPolicies.
func (s *concurrencySchedulingPolicyLister) ConcurrencySchedulingPolicies(namespace string) ConcurrencySchedulingPolicyNamespaceLister {
	return concurrencySchedulingPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ConcurrencySchedulingPolicyNamespaceLister helps list and get ConcurrencySchedulingPolicies.
// All objects returned here must be treated as read-only.
type ConcurrencySchedulingPolicyNamespaceLister interface {
	// List lists all ConcurrencySchedulingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ConcurrencySchedulingPolicy, err error)
	// Get retrieves the ConcurrencySchedulingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ConcurrencySchedulingPolicy, error)
	ConcurrencySchedulingPolicyNamespaceListerExpansion
}

// concurrencySchedulingPolicyNamespaceLister implements the ConcurrencySchedulingPolicyNamespaceLister
// interface.
type concurrencySchedulingPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ConcurrencySchedulingPolicies in the indexer for a given namespace.
func (s concurrencySchedulingPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.ConcurrencySchedulingPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ConcurrencySchedulingPolicy))
	})
	return ret, err
}

// Get retrieves the ConcurrencySchedulingPolicy from the indexer for a given namespace and name.
func (s concurrencySchedulingPolicyNamespaceLister) Get(name string) (*v1.ConcurrencySchedulingPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("concurrencyschedulingpolicy"), name)
	}
	return obj.(*v1.ConcurrencySchedulingPolicy), nil
}
