// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/ampere/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LoadRampingPolicyLister helps list LoadRampingPolicies.
// All objects returned here must be treated as read-only.
type LoadRampingPolicyLister interface {
	// List lists all LoadRampingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LoadRampingPolicy, err error)
	// LoadRampingPolicies returns an object that can list and get LoadRampingPolicies.
	LoadRampingPolicies(namespace string) LoadRampingPolicyNamespaceLister
	LoadRampingPolicyListerExpansion
}

// loadRampingPolicyLister implements the LoadRampingPolicyLister interface.
type loadRampingPolicyLister struct {
	indexer cache.Indexer
}

// NewLoadRampingPolicyLister returns a new LoadRampingPolicyLister.
func NewLoadRampingPolicyLister(indexer cache.Indexer) LoadRampingPolicyLister {
	return &loadRampingPolicyLister{indexer: indexer}
}

// List lists all LoadRampingPolicies in the indexer.
func (s *loadRampingPolicyLister) List(selector labels.Selector) (ret []*v1.LoadRampingPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LoadRampingPolicy))
	})
	return ret, err
}

// LoadRampingPolicies returns an object that can list and get LoadRampingPolicies.
func (s *loadRampingPolicyLister) LoadRampingPolicies(namespace string) LoadRampingPolicyNamespaceLister {
	return loadRampingPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// LoadRampingPolicyNamespaceLister helps list and get LoadRampingPolicies.
// All objects returned here must be treated as read-only.
type LoadRampingPolicyNamespaceLister interface {
	// List lists all LoadRampingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LoadRampingPolicy, err error)
	// Get retrieves the LoadRampingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.LoadRampingPolicy, error)
	LoadRampingPolicyNamespaceListerExpansion
}

// loadRampingPolicyNamespaceLister implements the LoadRampingPolicyNamespaceLister
// interface.
type loadRampingPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all LoadRampingPolicies in the indexer for a given namespace.
func (s loadRampingPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.LoadRampingPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LoadRampingPolicy))
	})
	return ret, err
}

// Get retrieves the LoadRampingPolicy from the indexer for a given namespace and name.
func (s loadRampingPolicyNamespaceLister) Get(name string) (*v1.LoadRampingPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("loadrampingpolicy"), name)
	}
	return obj.(*v1.LoadRampingPolicy), nil
}
