// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/ampere/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RateLimitingPolicyLister helps list RateLimitingPolicies.
// All objects returned here must be treated as read-only.
type RateLimitingPolicyLister interface {
	// List lists all RateLimitingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RateLimitingPolicy, err error)
	// RateLimitingPolicies returns an object that can list and get RateLimitingPolicies.
	RateLimitingPolicies(namespace string) RateLimitingPolicyNamespaceLister
	RateLimitingPolicyListerExpansion
}

// rateLimitingPolicyLister implements the RateLimitingPolicyLister interface.
type rateLimitingPolicyLister struct {
	indexer cache.Indexer
}

// NewRateLimitingPolicyLister returns a new RateLimitingPolicyLister.
func NewRateLimitingPolicyLister(indexer cache.Indexer) RateLimitingPolicyLister {
	return &rateLimitingPolicyLister{indexer: indexer}
}

// List lists all RateLimitingPolicies in the indexer.
func (s *rateLimitingPolicyLister) List(selector labels.Selector) (ret []*v1.RateLimitingPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.RateLimitingPolicy))
	})
	return ret, err
}

// RateLimitingPolicies returns an object that can list and get RateLimitingPolicies.
func (s *rateLimitingPolicyLister) RateLimitingPolicies(namespace string) RateLimitingPolicyNamespaceLister {
	return rateLimitingPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RateLimitingPolicyNamespaceLister helps list and get RateLimitingPolicies.
// All objects returned here must be treated as read-only.
type RateLimitingPolicyNamespaceLister interface {
	// List lists all RateLimitingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RateLimitingPolicy, err error)
	// Get retrieves the RateLimitingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.RateLimitingPolicy, error)
	RateLimitingPolicyNamespaceListerExpansion
}

// rateLimitingPolicyNamespaceLister implements the RateLimitingPolicyNamespaceLister
// interface.
type rateLimitingPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RateLimitingPolicies in the indexer for a given namespace.
func (s rateLimitingPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.RateLimitingPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.RateLimitingPolicy))
	})
	return ret, err
}

// Get retrieves the RateLimitingPolicy from the indexer for a given namespace and name.
func (s rateLimitingPolicyNamespaceLister) Get(name string) (*v1.RateLimitingPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("ratelimitingpolicy"), name)
	}
	return obj.(*v1.RateLimitingPolicy), nil
}
