// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	versioned "istio.io/client-go/asm/pkg/clientset/versioned"
	internalinterfaces "istio.io/client-go/asm/pkg/informers/externalversions/internalinterfaces"
	v1 "istio.io/client-go/asm/pkg/listers/alibabacloudservicemesh/v1"
	"context"
	time "time"

	alibabacloudservicemeshv1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ASMHashTaggingInformer provides access to a shared informer and lister for
// ASMHashTaggings.
type ASMHashTaggingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ASMHashTaggingLister
}

type aSMHashTaggingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewASMHashTaggingInformer constructs a new informer for ASMHashTagging type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewASMHashTaggingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredASMHashTaggingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredASMHashTaggingInformer constructs a new informer for ASMHashTagging type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredASMHashTaggingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IstioV1().ASMHashTaggings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IstioV1().ASMHashTaggings(namespace).Watch(context.TODO(), options)
			},
		},
		&alibabacloudservicemeshv1.ASMHashTagging{},
		resyncPeriod,
		indexers,
	)
}

func (f *aSMHashTaggingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredASMHashTaggingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aSMHashTaggingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alibabacloudservicemeshv1.ASMHashTagging{}, f.defaultInformer)
}

func (f *aSMHashTaggingInformer) Lister() v1.ASMHashTaggingLister {
	return v1.NewASMHashTaggingLister(f.Informer().GetIndexer())
}
