// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	clientset "istio.io/client-go/asm/pkg/clientset"
	internalinterfaces "istio.io/client-go/asm/pkg/informers/externalversions/internalinterfaces"
	v1 "istio.io/client-go/asm/pkg/listers/alibabacloudservicemesh/v1"
	"context"
	time "time"

	alibabacloudservicemeshv1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ASMSecurityPolicyInformer provides access to a shared informer and lister for
// ASMSecurityPolicies.
type ASMSecurityPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ASMSecurityPolicyLister
}

type aSMSecurityPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewASMSecurityPolicyInformer constructs a new informer for ASMSecurityPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewASMSecurityPolicyInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredASMSecurityPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredASMSecurityPolicyInformer constructs a new informer for ASMSecurityPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredASMSecurityPolicyInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IstioV1().ASMSecurityPolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IstioV1().ASMSecurityPolicies().Watch(context.TODO(), options)
			},
		},
		&alibabacloudservicemeshv1.ASMSecurityPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *aSMSecurityPolicyInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredASMSecurityPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aSMSecurityPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alibabacloudservicemeshv1.ASMSecurityPolicy{}, f.defaultInformer)
}

func (f *aSMSecurityPolicyInformer) Lister() v1.ASMSecurityPolicyLister {
	return v1.NewASMSecurityPolicyLister(f.Informer().GetIndexer())
}
