// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "istio.io/client-go/asm/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ASMAdaptiveConcurrencies returns a ASMAdaptiveConcurrencyInformer.
	ASMAdaptiveConcurrencies() ASMAdaptiveConcurrencyInformer
	// ASMCircuitBreakers returns a ASMCircuitBreakerInformer.
	ASMCircuitBreakers() ASMCircuitBreakerInformer
	// ASMEgressTrafficPolicies returns a ASMEgressTrafficPolicyInformer.
	ASMEgressTrafficPolicies() ASMEgressTrafficPolicyInformer
	// ASMLocalRateLimiters returns a ASMLocalRateLimiterInformer.
	ASMLocalRateLimiters() ASMLocalRateLimiterInformer
	// ASMSwimLanes returns a ASMSwimLaneInformer.
	ASMSwimLanes() ASMSwimLaneInformer
	// ASMSwimLaneGroups returns a ASMSwimLaneGroupInformer.
	ASMSwimLaneGroups() ASMSwimLaneGroupInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ASMAdaptiveConcurrencies returns a ASMAdaptiveConcurrencyInformer.
func (v *version) ASMAdaptiveConcurrencies() ASMAdaptiveConcurrencyInformer {
	return &aSMAdaptiveConcurrencyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMCircuitBreakers returns a ASMCircuitBreakerInformer.
func (v *version) ASMCircuitBreakers() ASMCircuitBreakerInformer {
	return &aSMCircuitBreakerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMEgressTrafficPolicies returns a ASMEgressTrafficPolicyInformer.
func (v *version) ASMEgressTrafficPolicies() ASMEgressTrafficPolicyInformer {
	return &aSMEgressTrafficPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMLocalRateLimiters returns a ASMLocalRateLimiterInformer.
func (v *version) ASMLocalRateLimiters() ASMLocalRateLimiterInformer {
	return &aSMLocalRateLimiterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMSwimLanes returns a ASMSwimLaneInformer.
func (v *version) ASMSwimLanes() ASMSwimLaneInformer {
	return &aSMSwimLaneInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMSwimLaneGroups returns a ASMSwimLaneGroupInformer.
func (v *version) ASMSwimLaneGroups() ASMSwimLaneGroupInformer {
	return &aSMSwimLaneGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
