// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "istio.io/client-go/asm/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ASMAdaptiveConcurrencies returns a ASMAdaptiveConcurrencyInformer.
	ASMAdaptiveConcurrencies() ASMAdaptiveConcurrencyInformer
	// ASMCircuitBreakers returns a ASMCircuitBreakerInformer.
	ASMCircuitBreakers() ASMCircuitBreakerInformer
	// ASMCompressors returns a ASMCompressorInformer.
	ASMCompressors() ASMCompressorInformer
	// ASMCredentials returns a ASMCredentialInformer.
	ASMCredentials() ASMCredentialInformer
	// ASMCustomProxyConfigInjectionTemplates returns a ASMCustomProxyConfigInjectionTemplateInformer.
	ASMCustomProxyConfigInjectionTemplates() ASMCustomProxyConfigInjectionTemplateInformer
	// ASMDecompressors returns a ASMDecompressorInformer.
	ASMDecompressors() ASMDecompressorInformer
	// ASMEgressTrafficPolicies returns a ASMEgressTrafficPolicyInformer.
	ASMEgressTrafficPolicies() ASMEgressTrafficPolicyInformer
	// ASMExtensionProviders returns a ASMExtensionProviderInformer.
	ASMExtensionProviders() ASMExtensionProviderInformer
	// ASMGlobalRateLimiters returns a ASMGlobalRateLimiterInformer.
	ASMGlobalRateLimiters() ASMGlobalRateLimiterInformer
	// ASMGrpcJsonTranscoders returns a ASMGrpcJsonTranscoderInformer.
	ASMGrpcJsonTranscoders() ASMGrpcJsonTranscoderInformer
	// ASMKServeConfigs returns a ASMKServeConfigInformer.
	ASMKServeConfigs() ASMKServeConfigInformer
	// ASMKnativeConfigs returns a ASMKnativeConfigInformer.
	ASMKnativeConfigs() ASMKnativeConfigInformer
	// ASMLocalRateLimiters returns a ASMLocalRateLimiterInformer.
	ASMLocalRateLimiters() ASMLocalRateLimiterInformer
	// ASMMigrateFromIstios returns a ASMMigrateFromIstioInformer.
	ASMMigrateFromIstios() ASMMigrateFromIstioInformer
	// ASMPacketInspectors returns a ASMPacketInspectorInformer.
	ASMPacketInspectors() ASMPacketInspectorInformer
	// ASMProxyConfigs returns a ASMProxyConfigInformer.
	ASMProxyConfigs() ASMProxyConfigInformer
	// ASMSecurityPolicies returns a ASMSecurityPolicyInformer.
	ASMSecurityPolicies() ASMSecurityPolicyInformer
	// ASMSwimLanes returns a ASMSwimLaneInformer.
	ASMSwimLanes() ASMSwimLaneInformer
	// ASMSwimLaneGroups returns a ASMSwimLaneGroupInformer.
	ASMSwimLaneGroups() ASMSwimLaneGroupInformer
	// EnvoyFilterTemplates returns a EnvoyFilterTemplateInformer.
	EnvoyFilterTemplates() EnvoyFilterTemplateInformer
	// EnvoyFilterTemplateBindings returns a EnvoyFilterTemplateBindingInformer.
	EnvoyFilterTemplateBindings() EnvoyFilterTemplateBindingInformer
	// IstioGateways returns a IstioGatewayInformer.
	IstioGateways() IstioGatewayInformer
	// LLMProviders returns a LLMProviderInformer.
	LLMProviders() LLMProviderInformer
	// LLMRoutes returns a LLMRouteInformer.
	LLMRoutes() LLMRouteInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ASMAdaptiveConcurrencies returns a ASMAdaptiveConcurrencyInformer.
func (v *version) ASMAdaptiveConcurrencies() ASMAdaptiveConcurrencyInformer {
	return &aSMAdaptiveConcurrencyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMCircuitBreakers returns a ASMCircuitBreakerInformer.
func (v *version) ASMCircuitBreakers() ASMCircuitBreakerInformer {
	return &aSMCircuitBreakerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMCompressors returns a ASMCompressorInformer.
func (v *version) ASMCompressors() ASMCompressorInformer {
	return &aSMCompressorInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMCredentials returns a ASMCredentialInformer.
func (v *version) ASMCredentials() ASMCredentialInformer {
	return &aSMCredentialInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMCustomProxyConfigInjectionTemplates returns a ASMCustomProxyConfigInjectionTemplateInformer.
func (v *version) ASMCustomProxyConfigInjectionTemplates() ASMCustomProxyConfigInjectionTemplateInformer {
	return &aSMCustomProxyConfigInjectionTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMDecompressors returns a ASMDecompressorInformer.
func (v *version) ASMDecompressors() ASMDecompressorInformer {
	return &aSMDecompressorInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMEgressTrafficPolicies returns a ASMEgressTrafficPolicyInformer.
func (v *version) ASMEgressTrafficPolicies() ASMEgressTrafficPolicyInformer {
	return &aSMEgressTrafficPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMExtensionProviders returns a ASMExtensionProviderInformer.
func (v *version) ASMExtensionProviders() ASMExtensionProviderInformer {
	return &aSMExtensionProviderInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMGlobalRateLimiters returns a ASMGlobalRateLimiterInformer.
func (v *version) ASMGlobalRateLimiters() ASMGlobalRateLimiterInformer {
	return &aSMGlobalRateLimiterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMGrpcJsonTranscoders returns a ASMGrpcJsonTranscoderInformer.
func (v *version) ASMGrpcJsonTranscoders() ASMGrpcJsonTranscoderInformer {
	return &aSMGrpcJsonTranscoderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMKServeConfigs returns a ASMKServeConfigInformer.
func (v *version) ASMKServeConfigs() ASMKServeConfigInformer {
	return &aSMKServeConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMKnativeConfigs returns a ASMKnativeConfigInformer.
func (v *version) ASMKnativeConfigs() ASMKnativeConfigInformer {
	return &aSMKnativeConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMLocalRateLimiters returns a ASMLocalRateLimiterInformer.
func (v *version) ASMLocalRateLimiters() ASMLocalRateLimiterInformer {
	return &aSMLocalRateLimiterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMMigrateFromIstios returns a ASMMigrateFromIstioInformer.
func (v *version) ASMMigrateFromIstios() ASMMigrateFromIstioInformer {
	return &aSMMigrateFromIstioInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMPacketInspectors returns a ASMPacketInspectorInformer.
func (v *version) ASMPacketInspectors() ASMPacketInspectorInformer {
	return &aSMPacketInspectorInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMProxyConfigs returns a ASMProxyConfigInformer.
func (v *version) ASMProxyConfigs() ASMProxyConfigInformer {
	return &aSMProxyConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ASMSecurityPolicies returns a ASMSecurityPolicyInformer.
func (v *version) ASMSecurityPolicies() ASMSecurityPolicyInformer {
	return &aSMSecurityPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMSwimLanes returns a ASMSwimLaneInformer.
func (v *version) ASMSwimLanes() ASMSwimLaneInformer {
	return &aSMSwimLaneInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ASMSwimLaneGroups returns a ASMSwimLaneGroupInformer.
func (v *version) ASMSwimLaneGroups() ASMSwimLaneGroupInformer {
	return &aSMSwimLaneGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// EnvoyFilterTemplates returns a EnvoyFilterTemplateInformer.
func (v *version) EnvoyFilterTemplates() EnvoyFilterTemplateInformer {
	return &envoyFilterTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// EnvoyFilterTemplateBindings returns a EnvoyFilterTemplateBindingInformer.
func (v *version) EnvoyFilterTemplateBindings() EnvoyFilterTemplateBindingInformer {
	return &envoyFilterTemplateBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IstioGateways returns a IstioGatewayInformer.
func (v *version) IstioGateways() IstioGatewayInformer {
	return &istioGatewayInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LLMProviders returns a LLMProviderInformer.
func (v *version) LLMProviders() LLMProviderInformer {
	return &lLMProviderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LLMRoutes returns a LLMRouteInformer.
func (v *version) LLMRoutes() LLMRouteInformer {
	return &lLMRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
