// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloud-servicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMAdaptiveConcurrencies implements ASMAdaptiveConcurrencyInterface
type FakeASMAdaptiveConcurrencies struct {
	Fake *FakeIstioV1
	ns   string
}

var asmadaptiveconcurrenciesResource = v1.SchemeGroupVersion.WithResource("asmadaptiveconcurrencies")

var asmadaptiveconcurrenciesKind = v1.SchemeGroupVersion.WithKind("ASMAdaptiveConcurrency")

// Get takes name of the aSMAdaptiveConcurrency, and returns the corresponding aSMAdaptiveConcurrency object, and an error if there is any.
func (c *FakeASMAdaptiveConcurrencies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMAdaptiveConcurrency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmadaptiveconcurrenciesResource, c.ns, name), &v1.ASMAdaptiveConcurrency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMAdaptiveConcurrency), err
}

// List takes label and field selectors, and returns the list of ASMAdaptiveConcurrencies that match those selectors.
func (c *FakeASMAdaptiveConcurrencies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMAdaptiveConcurrencyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmadaptiveconcurrenciesResource, asmadaptiveconcurrenciesKind, c.ns, opts), &v1.ASMAdaptiveConcurrencyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMAdaptiveConcurrencyList{ListMeta: obj.(*v1.ASMAdaptiveConcurrencyList).ListMeta}
	for _, item := range obj.(*v1.ASMAdaptiveConcurrencyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMAdaptiveConcurrencies.
func (c *FakeASMAdaptiveConcurrencies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmadaptiveconcurrenciesResource, c.ns, opts))

}

// Create takes the representation of a aSMAdaptiveConcurrency and creates it.  Returns the server's representation of the aSMAdaptiveConcurrency, and an error, if there is any.
func (c *FakeASMAdaptiveConcurrencies) Create(ctx context.Context, aSMAdaptiveConcurrency *v1.ASMAdaptiveConcurrency, opts metav1.CreateOptions) (result *v1.ASMAdaptiveConcurrency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmadaptiveconcurrenciesResource, c.ns, aSMAdaptiveConcurrency), &v1.ASMAdaptiveConcurrency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMAdaptiveConcurrency), err
}

// Update takes the representation of a aSMAdaptiveConcurrency and updates it. Returns the server's representation of the aSMAdaptiveConcurrency, and an error, if there is any.
func (c *FakeASMAdaptiveConcurrencies) Update(ctx context.Context, aSMAdaptiveConcurrency *v1.ASMAdaptiveConcurrency, opts metav1.UpdateOptions) (result *v1.ASMAdaptiveConcurrency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmadaptiveconcurrenciesResource, c.ns, aSMAdaptiveConcurrency), &v1.ASMAdaptiveConcurrency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMAdaptiveConcurrency), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMAdaptiveConcurrencies) UpdateStatus(ctx context.Context, aSMAdaptiveConcurrency *v1.ASMAdaptiveConcurrency, opts metav1.UpdateOptions) (*v1.ASMAdaptiveConcurrency, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmadaptiveconcurrenciesResource, "status", c.ns, aSMAdaptiveConcurrency), &v1.ASMAdaptiveConcurrency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMAdaptiveConcurrency), err
}

// Delete takes name of the aSMAdaptiveConcurrency and deletes it. Returns an error if one occurs.
func (c *FakeASMAdaptiveConcurrencies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmadaptiveconcurrenciesResource, c.ns, name, opts), &v1.ASMAdaptiveConcurrency{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMAdaptiveConcurrencies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmadaptiveconcurrenciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMAdaptiveConcurrencyList{})
	return err
}

// Patch applies the patch and returns the patched aSMAdaptiveConcurrency.
func (c *FakeASMAdaptiveConcurrencies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMAdaptiveConcurrency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmadaptiveconcurrenciesResource, c.ns, name, pt, data, subresources...), &v1.ASMAdaptiveConcurrency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMAdaptiveConcurrency), err
}
