// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/scheme"
	"context"
	"time"

	v1 "istio.io/api/alibabacloud-servicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ASMSwimLaneGroupsGetter has a method to return a ASMSwimLaneGroupInterface.
// A group's client should implement this interface.
type ASMSwimLaneGroupsGetter interface {
	ASMSwimLaneGroups() ASMSwimLaneGroupInterface
}

// ASMSwimLaneGroupInterface has methods to work with ASMSwimLaneGroup resources.
type ASMSwimLaneGroupInterface interface {
	Create(ctx context.Context, aSMSwimLaneGroup *v1.ASMSwimLaneGroup, opts metav1.CreateOptions) (*v1.ASMSwimLaneGroup, error)
	Update(ctx context.Context, aSMSwimLaneGroup *v1.ASMSwimLaneGroup, opts metav1.UpdateOptions) (*v1.ASMSwimLaneGroup, error)
	UpdateStatus(ctx context.Context, aSMSwimLaneGroup *v1.ASMSwimLaneGroup, opts metav1.UpdateOptions) (*v1.ASMSwimLaneGroup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ASMSwimLaneGroup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ASMSwimLaneGroupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMSwimLaneGroup, err error)
	ASMSwimLaneGroupExpansion
}

// aSMSwimLaneGroups implements ASMSwimLaneGroupInterface
type aSMSwimLaneGroups struct {
	client rest.Interface
}

// newASMSwimLaneGroups returns a ASMSwimLaneGroups
func newASMSwimLaneGroups(c *IstioV1Client) *aSMSwimLaneGroups {
	return &aSMSwimLaneGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the aSMSwimLaneGroup, and returns the corresponding aSMSwimLaneGroup object, and an error if there is any.
func (c *aSMSwimLaneGroups) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMSwimLaneGroup, err error) {
	result = &v1.ASMSwimLaneGroup{}
	err = c.client.Get().
		Resource("asmswimlanegroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ASMSwimLaneGroups that match those selectors.
func (c *aSMSwimLaneGroups) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMSwimLaneGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ASMSwimLaneGroupList{}
	err = c.client.Get().
		Resource("asmswimlanegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aSMSwimLaneGroups.
func (c *aSMSwimLaneGroups) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("asmswimlanegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aSMSwimLaneGroup and creates it.  Returns the server's representation of the aSMSwimLaneGroup, and an error, if there is any.
func (c *aSMSwimLaneGroups) Create(ctx context.Context, aSMSwimLaneGroup *v1.ASMSwimLaneGroup, opts metav1.CreateOptions) (result *v1.ASMSwimLaneGroup, err error) {
	result = &v1.ASMSwimLaneGroup{}
	err = c.client.Post().
		Resource("asmswimlanegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMSwimLaneGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aSMSwimLaneGroup and updates it. Returns the server's representation of the aSMSwimLaneGroup, and an error, if there is any.
func (c *aSMSwimLaneGroups) Update(ctx context.Context, aSMSwimLaneGroup *v1.ASMSwimLaneGroup, opts metav1.UpdateOptions) (result *v1.ASMSwimLaneGroup, err error) {
	result = &v1.ASMSwimLaneGroup{}
	err = c.client.Put().
		Resource("asmswimlanegroups").
		Name(aSMSwimLaneGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMSwimLaneGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aSMSwimLaneGroups) UpdateStatus(ctx context.Context, aSMSwimLaneGroup *v1.ASMSwimLaneGroup, opts metav1.UpdateOptions) (result *v1.ASMSwimLaneGroup, err error) {
	result = &v1.ASMSwimLaneGroup{}
	err = c.client.Put().
		Resource("asmswimlanegroups").
		Name(aSMSwimLaneGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMSwimLaneGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aSMSwimLaneGroup and deletes it. Returns an error if one occurs.
func (c *aSMSwimLaneGroups) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("asmswimlanegroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aSMSwimLaneGroups) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("asmswimlanegroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aSMSwimLaneGroup.
func (c *aSMSwimLaneGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMSwimLaneGroup, err error) {
	result = &v1.ASMSwimLaneGroup{}
	err = c.client.Patch(pt).
		Resource("asmswimlanegroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
