// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ASMCompressorLister helps list ASMCompressors.
// All objects returned here must be treated as read-only.
type ASMCompressorLister interface {
	// List lists all ASMCompressors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMCompressor, err error)
	// ASMCompressors returns an object that can list and get ASMCompressors.
	ASMCompressors(namespace string) ASMCompressorNamespaceLister
	ASMCompressorListerExpansion
}

// aSMCompressorLister implements the ASMCompressorLister interface.
type aSMCompressorLister struct {
	indexer cache.Indexer
}

// NewASMCompressorLister returns a new ASMCompressorLister.
func NewASMCompressorLister(indexer cache.Indexer) ASMCompressorLister {
	return &aSMCompressorLister{indexer: indexer}
}

// List lists all ASMCompressors in the indexer.
func (s *aSMCompressorLister) List(selector labels.Selector) (ret []*v1.ASMCompressor, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMCompressor))
	})
	return ret, err
}

// ASMCompressors returns an object that can list and get ASMCompressors.
func (s *aSMCompressorLister) ASMCompressors(namespace string) ASMCompressorNamespaceLister {
	return aSMCompressorNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ASMCompressorNamespaceLister helps list and get ASMCompressors.
// All objects returned here must be treated as read-only.
type ASMCompressorNamespaceLister interface {
	// List lists all ASMCompressors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMCompressor, err error)
	// Get retrieves the ASMCompressor from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ASMCompressor, error)
	ASMCompressorNamespaceListerExpansion
}

// aSMCompressorNamespaceLister implements the ASMCompressorNamespaceLister
// interface.
type aSMCompressorNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ASMCompressors in the indexer for a given namespace.
func (s aSMCompressorNamespaceLister) List(selector labels.Selector) (ret []*v1.ASMCompressor, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMCompressor))
	})
	return ret, err
}

// Get retrieves the ASMCompressor from the indexer for a given namespace and name.
func (s aSMCompressorNamespaceLister) Get(name string) (*v1.ASMCompressor, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("asmcompressor"), name)
	}
	return obj.(*v1.ASMCompressor), nil
}
