// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ASMDecompressorLister helps list ASMDecompressors.
// All objects returned here must be treated as read-only.
type ASMDecompressorLister interface {
	// List lists all ASMDecompressors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMDecompressor, err error)
	// ASMDecompressors returns an object that can list and get ASMDecompressors.
	ASMDecompressors(namespace string) ASMDecompressorNamespaceLister
	ASMDecompressorListerExpansion
}

// aSMDecompressorLister implements the ASMDecompressorLister interface.
type aSMDecompressorLister struct {
	indexer cache.Indexer
}

// NewASMDecompressorLister returns a new ASMDecompressorLister.
func NewASMDecompressorLister(indexer cache.Indexer) ASMDecompressorLister {
	return &aSMDecompressorLister{indexer: indexer}
}

// List lists all ASMDecompressors in the indexer.
func (s *aSMDecompressorLister) List(selector labels.Selector) (ret []*v1.ASMDecompressor, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMDecompressor))
	})
	return ret, err
}

// ASMDecompressors returns an object that can list and get ASMDecompressors.
func (s *aSMDecompressorLister) ASMDecompressors(namespace string) ASMDecompressorNamespaceLister {
	return aSMDecompressorNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ASMDecompressorNamespaceLister helps list and get ASMDecompressors.
// All objects returned here must be treated as read-only.
type ASMDecompressorNamespaceLister interface {
	// List lists all ASMDecompressors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMDecompressor, err error)
	// Get retrieves the ASMDecompressor from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ASMDecompressor, error)
	ASMDecompressorNamespaceListerExpansion
}

// aSMDecompressorNamespaceLister implements the ASMDecompressorNamespaceLister
// interface.
type aSMDecompressorNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ASMDecompressors in the indexer for a given namespace.
func (s aSMDecompressorNamespaceLister) List(selector labels.Selector) (ret []*v1.ASMDecompressor, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMDecompressor))
	})
	return ret, err
}

// Get retrieves the ASMDecompressor from the indexer for a given namespace and name.
func (s aSMDecompressorNamespaceLister) Get(name string) (*v1.ASMDecompressor, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("asmdecompressor"), name)
	}
	return obj.(*v1.ASMDecompressor), nil
}
