// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ASMEgressTrafficPolicyLister helps list ASMEgressTrafficPolicies.
// All objects returned here must be treated as read-only.
type ASMEgressTrafficPolicyLister interface {
	// List lists all ASMEgressTrafficPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMEgressTrafficPolicy, err error)
	// ASMEgressTrafficPolicies returns an object that can list and get ASMEgressTrafficPolicies.
	ASMEgressTrafficPolicies(namespace string) ASMEgressTrafficPolicyNamespaceLister
	ASMEgressTrafficPolicyListerExpansion
}

// aSMEgressTrafficPolicyLister implements the ASMEgressTrafficPolicyLister interface.
type aSMEgressTrafficPolicyLister struct {
	indexer cache.Indexer
}

// NewASMEgressTrafficPolicyLister returns a new ASMEgressTrafficPolicyLister.
func NewASMEgressTrafficPolicyLister(indexer cache.Indexer) ASMEgressTrafficPolicyLister {
	return &aSMEgressTrafficPolicyLister{indexer: indexer}
}

// List lists all ASMEgressTrafficPolicies in the indexer.
func (s *aSMEgressTrafficPolicyLister) List(selector labels.Selector) (ret []*v1.ASMEgressTrafficPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMEgressTrafficPolicy))
	})
	return ret, err
}

// ASMEgressTrafficPolicies returns an object that can list and get ASMEgressTrafficPolicies.
func (s *aSMEgressTrafficPolicyLister) ASMEgressTrafficPolicies(namespace string) ASMEgressTrafficPolicyNamespaceLister {
	return aSMEgressTrafficPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ASMEgressTrafficPolicyNamespaceLister helps list and get ASMEgressTrafficPolicies.
// All objects returned here must be treated as read-only.
type ASMEgressTrafficPolicyNamespaceLister interface {
	// List lists all ASMEgressTrafficPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMEgressTrafficPolicy, err error)
	// Get retrieves the ASMEgressTrafficPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ASMEgressTrafficPolicy, error)
	ASMEgressTrafficPolicyNamespaceListerExpansion
}

// aSMEgressTrafficPolicyNamespaceLister implements the ASMEgressTrafficPolicyNamespaceLister
// interface.
type aSMEgressTrafficPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ASMEgressTrafficPolicies in the indexer for a given namespace.
func (s aSMEgressTrafficPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1.ASMEgressTrafficPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMEgressTrafficPolicy))
	})
	return ret, err
}

// Get retrieves the ASMEgressTrafficPolicy from the indexer for a given namespace and name.
func (s aSMEgressTrafficPolicyNamespaceLister) Get(name string) (*v1.ASMEgressTrafficPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("asmegresstrafficpolicy"), name)
	}
	return obj.(*v1.ASMEgressTrafficPolicy), nil
}
