// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ASMGrpcJsonTranscoderLister helps list ASMGrpcJsonTranscoders.
// All objects returned here must be treated as read-only.
type ASMGrpcJsonTranscoderLister interface {
	// List lists all ASMGrpcJsonTranscoders in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMGrpcJsonTranscoder, err error)
	// ASMGrpcJsonTranscoders returns an object that can list and get ASMGrpcJsonTranscoders.
	ASMGrpcJsonTranscoders(namespace string) ASMGrpcJsonTranscoderNamespaceLister
	ASMGrpcJsonTranscoderListerExpansion
}

// aSMGrpcJsonTranscoderLister implements the ASMGrpcJsonTranscoderLister interface.
type aSMGrpcJsonTranscoderLister struct {
	indexer cache.Indexer
}

// NewASMGrpcJsonTranscoderLister returns a new ASMGrpcJsonTranscoderLister.
func NewASMGrpcJsonTranscoderLister(indexer cache.Indexer) ASMGrpcJsonTranscoderLister {
	return &aSMGrpcJsonTranscoderLister{indexer: indexer}
}

// List lists all ASMGrpcJsonTranscoders in the indexer.
func (s *aSMGrpcJsonTranscoderLister) List(selector labels.Selector) (ret []*v1.ASMGrpcJsonTranscoder, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMGrpcJsonTranscoder))
	})
	return ret, err
}

// ASMGrpcJsonTranscoders returns an object that can list and get ASMGrpcJsonTranscoders.
func (s *aSMGrpcJsonTranscoderLister) ASMGrpcJsonTranscoders(namespace string) ASMGrpcJsonTranscoderNamespaceLister {
	return aSMGrpcJsonTranscoderNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ASMGrpcJsonTranscoderNamespaceLister helps list and get ASMGrpcJsonTranscoders.
// All objects returned here must be treated as read-only.
type ASMGrpcJsonTranscoderNamespaceLister interface {
	// List lists all ASMGrpcJsonTranscoders in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ASMGrpcJsonTranscoder, err error)
	// Get retrieves the ASMGrpcJsonTranscoder from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ASMGrpcJsonTranscoder, error)
	ASMGrpcJsonTranscoderNamespaceListerExpansion
}

// aSMGrpcJsonTranscoderNamespaceLister implements the ASMGrpcJsonTranscoderNamespaceLister
// interface.
type aSMGrpcJsonTranscoderNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ASMGrpcJsonTranscoders in the indexer for a given namespace.
func (s aSMGrpcJsonTranscoderNamespaceLister) List(selector labels.Selector) (ret []*v1.ASMGrpcJsonTranscoder, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ASMGrpcJsonTranscoder))
	})
	return ret, err
}

// Get retrieves the ASMGrpcJsonTranscoder from the indexer for a given namespace and name.
func (s aSMGrpcJsonTranscoderNamespaceLister) Get(name string) (*v1.ASMGrpcJsonTranscoder, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("asmgrpcjsontranscoder"), name)
	}
	return obj.(*v1.ASMGrpcJsonTranscoder), nil
}
