// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EnvoyFilterTemplateBindingLister helps list EnvoyFilterTemplateBindings.
// All objects returned here must be treated as read-only.
type EnvoyFilterTemplateBindingLister interface {
	// List lists all EnvoyFilterTemplateBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.EnvoyFilterTemplateBinding, err error)
	// EnvoyFilterTemplateBindings returns an object that can list and get EnvoyFilterTemplateBindings.
	EnvoyFilterTemplateBindings(namespace string) EnvoyFilterTemplateBindingNamespaceLister
	EnvoyFilterTemplateBindingListerExpansion
}

// envoyFilterTemplateBindingLister implements the EnvoyFilterTemplateBindingLister interface.
type envoyFilterTemplateBindingLister struct {
	indexer cache.Indexer
}

// NewEnvoyFilterTemplateBindingLister returns a new EnvoyFilterTemplateBindingLister.
func NewEnvoyFilterTemplateBindingLister(indexer cache.Indexer) EnvoyFilterTemplateBindingLister {
	return &envoyFilterTemplateBindingLister{indexer: indexer}
}

// List lists all EnvoyFilterTemplateBindings in the indexer.
func (s *envoyFilterTemplateBindingLister) List(selector labels.Selector) (ret []*v1.EnvoyFilterTemplateBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.EnvoyFilterTemplateBinding))
	})
	return ret, err
}

// EnvoyFilterTemplateBindings returns an object that can list and get EnvoyFilterTemplateBindings.
func (s *envoyFilterTemplateBindingLister) EnvoyFilterTemplateBindings(namespace string) EnvoyFilterTemplateBindingNamespaceLister {
	return envoyFilterTemplateBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// EnvoyFilterTemplateBindingNamespaceLister helps list and get EnvoyFilterTemplateBindings.
// All objects returned here must be treated as read-only.
type EnvoyFilterTemplateBindingNamespaceLister interface {
	// List lists all EnvoyFilterTemplateBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.EnvoyFilterTemplateBinding, err error)
	// Get retrieves the EnvoyFilterTemplateBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.EnvoyFilterTemplateBinding, error)
	EnvoyFilterTemplateBindingNamespaceListerExpansion
}

// envoyFilterTemplateBindingNamespaceLister implements the EnvoyFilterTemplateBindingNamespaceLister
// interface.
type envoyFilterTemplateBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all EnvoyFilterTemplateBindings in the indexer for a given namespace.
func (s envoyFilterTemplateBindingNamespaceLister) List(selector labels.Selector) (ret []*v1.EnvoyFilterTemplateBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.EnvoyFilterTemplateBinding))
	})
	return ret, err
}

// Get retrieves the EnvoyFilterTemplateBinding from the indexer for a given namespace and name.
func (s envoyFilterTemplateBindingNamespaceLister) Get(name string) (*v1.EnvoyFilterTemplateBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("envoyfiltertemplatebinding"), name)
	}
	return obj.(*v1.EnvoyFilterTemplateBinding), nil
}
