// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

// ASMAdaptiveConcurrencyListerExpansion allows custom methods to be added to
// ASMAdaptiveConcurrencyLister.
type ASMAdaptiveConcurrencyListerExpansion interface{}

// ASMAdaptiveConcurrencyNamespaceListerExpansion allows custom methods to be added to
// ASMAdaptiveConcurrencyNamespaceLister.
type ASMAdaptiveConcurrencyNamespaceListerExpansion interface{}

// ASMCircuitBreakerListerExpansion allows custom methods to be added to
// ASMCircuitBreakerLister.
type ASMCircuitBreakerListerExpansion interface{}

// ASMCircuitBreakerNamespaceListerExpansion allows custom methods to be added to
// ASMCircuitBreakerNamespaceLister.
type ASMCircuitBreakerNamespaceListerExpansion interface{}

// ASMEgressTrafficPolicyListerExpansion allows custom methods to be added to
// ASMEgressTrafficPolicyLister.
type ASMEgressTrafficPolicyListerExpansion interface{}

// ASMEgressTrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// ASMEgressTrafficPolicyNamespaceLister.
type ASMEgressTrafficPolicyNamespaceListerExpansion interface{}

// ASMLocalRateLimiterListerExpansion allows custom methods to be added to
// ASMLocalRateLimiterLister.
type ASMLocalRateLimiterListerExpansion interface{}

// ASMLocalRateLimiterNamespaceListerExpansion allows custom methods to be added to
// ASMLocalRateLimiterNamespaceLister.
type ASMLocalRateLimiterNamespaceListerExpansion interface{}

// ASMSwimLaneListerExpansion allows custom methods to be added to
// ASMSwimLaneLister.
type ASMSwimLaneListerExpansion interface{}

// ASMSwimLaneGroupListerExpansion allows custom methods to be added to
// ASMSwimLaneGroupLister.
type ASMSwimLaneGroupListerExpansion interface{}
