// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

// ASMAdaptiveConcurrencyListerExpansion allows custom methods to be added to
// ASMAdaptiveConcurrencyLister.
type ASMAdaptiveConcurrencyListerExpansion interface{}

// ASMAdaptiveConcurrencyNamespaceListerExpansion allows custom methods to be added to
// ASMAdaptiveConcurrencyNamespaceLister.
type ASMAdaptiveConcurrencyNamespaceListerExpansion interface{}

// ASMCircuitBreakerListerExpansion allows custom methods to be added to
// ASMCircuitBreakerLister.
type ASMCircuitBreakerListerExpansion interface{}

// ASMCircuitBreakerNamespaceListerExpansion allows custom methods to be added to
// ASMCircuitBreakerNamespaceLister.
type ASMCircuitBreakerNamespaceListerExpansion interface{}

// ASMCompressorListerExpansion allows custom methods to be added to
// ASMCompressorLister.
type ASMCompressorListerExpansion interface{}

// ASMCompressorNamespaceListerExpansion allows custom methods to be added to
// ASMCompressorNamespaceLister.
type ASMCompressorNamespaceListerExpansion interface{}

// ASMCredentialListerExpansion allows custom methods to be added to
// ASMCredentialLister.
type ASMCredentialListerExpansion interface{}

// ASMCredentialNamespaceListerExpansion allows custom methods to be added to
// ASMCredentialNamespaceLister.
type ASMCredentialNamespaceListerExpansion interface{}

// ASMCustomProxyConfigInjectionTemplateListerExpansion allows custom methods to be added to
// ASMCustomProxyConfigInjectionTemplateLister.
type ASMCustomProxyConfigInjectionTemplateListerExpansion interface{}

// ASMCustomProxyConfigInjectionTemplateNamespaceListerExpansion allows custom methods to be added to
// ASMCustomProxyConfigInjectionTemplateNamespaceLister.
type ASMCustomProxyConfigInjectionTemplateNamespaceListerExpansion interface{}

// ASMDecompressorListerExpansion allows custom methods to be added to
// ASMDecompressorLister.
type ASMDecompressorListerExpansion interface{}

// ASMDecompressorNamespaceListerExpansion allows custom methods to be added to
// ASMDecompressorNamespaceLister.
type ASMDecompressorNamespaceListerExpansion interface{}

// ASMEgressTrafficPolicyListerExpansion allows custom methods to be added to
// ASMEgressTrafficPolicyLister.
type ASMEgressTrafficPolicyListerExpansion interface{}

// ASMEgressTrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// ASMEgressTrafficPolicyNamespaceLister.
type ASMEgressTrafficPolicyNamespaceListerExpansion interface{}

// ASMExtensionProviderListerExpansion allows custom methods to be added to
// ASMExtensionProviderLister.
type ASMExtensionProviderListerExpansion interface{}

// ASMGlobalRateLimiterListerExpansion allows custom methods to be added to
// ASMGlobalRateLimiterLister.
type ASMGlobalRateLimiterListerExpansion interface{}

// ASMGlobalRateLimiterNamespaceListerExpansion allows custom methods to be added to
// ASMGlobalRateLimiterNamespaceLister.
type ASMGlobalRateLimiterNamespaceListerExpansion interface{}

// ASMGrpcJsonTranscoderListerExpansion allows custom methods to be added to
// ASMGrpcJsonTranscoderLister.
type ASMGrpcJsonTranscoderListerExpansion interface{}

// ASMGrpcJsonTranscoderNamespaceListerExpansion allows custom methods to be added to
// ASMGrpcJsonTranscoderNamespaceLister.
type ASMGrpcJsonTranscoderNamespaceListerExpansion interface{}

// ASMKServeConfigListerExpansion allows custom methods to be added to
// ASMKServeConfigLister.
type ASMKServeConfigListerExpansion interface{}

// ASMKnativeConfigListerExpansion allows custom methods to be added to
// ASMKnativeConfigLister.
type ASMKnativeConfigListerExpansion interface{}

// ASMLocalRateLimiterListerExpansion allows custom methods to be added to
// ASMLocalRateLimiterLister.
type ASMLocalRateLimiterListerExpansion interface{}

// ASMLocalRateLimiterNamespaceListerExpansion allows custom methods to be added to
// ASMLocalRateLimiterNamespaceLister.
type ASMLocalRateLimiterNamespaceListerExpansion interface{}

// ASMMigrateFromIstioListerExpansion allows custom methods to be added to
// ASMMigrateFromIstioLister.
type ASMMigrateFromIstioListerExpansion interface{}

// ASMPacketInspectorListerExpansion allows custom methods to be added to
// ASMPacketInspectorLister.
type ASMPacketInspectorListerExpansion interface{}

// ASMProxyConfigListerExpansion allows custom methods to be added to
// ASMProxyConfigLister.
type ASMProxyConfigListerExpansion interface{}

// ASMProxyConfigNamespaceListerExpansion allows custom methods to be added to
// ASMProxyConfigNamespaceLister.
type ASMProxyConfigNamespaceListerExpansion interface{}

// ASMSecurityPolicyListerExpansion allows custom methods to be added to
// ASMSecurityPolicyLister.
type ASMSecurityPolicyListerExpansion interface{}

// ASMSwimLaneListerExpansion allows custom methods to be added to
// ASMSwimLaneLister.
type ASMSwimLaneListerExpansion interface{}

// ASMSwimLaneGroupListerExpansion allows custom methods to be added to
// ASMSwimLaneGroupLister.
type ASMSwimLaneGroupListerExpansion interface{}

// EnvoyFilterTemplateListerExpansion allows custom methods to be added to
// EnvoyFilterTemplateLister.
type EnvoyFilterTemplateListerExpansion interface{}

// EnvoyFilterTemplateNamespaceListerExpansion allows custom methods to be added to
// EnvoyFilterTemplateNamespaceLister.
type EnvoyFilterTemplateNamespaceListerExpansion interface{}

// EnvoyFilterTemplateBindingListerExpansion allows custom methods to be added to
// EnvoyFilterTemplateBindingLister.
type EnvoyFilterTemplateBindingListerExpansion interface{}

// EnvoyFilterTemplateBindingNamespaceListerExpansion allows custom methods to be added to
// EnvoyFilterTemplateBindingNamespaceLister.
type EnvoyFilterTemplateBindingNamespaceListerExpansion interface{}

// IstioGatewayListerExpansion allows custom methods to be added to
// IstioGatewayLister.
type IstioGatewayListerExpansion interface{}

// IstioGatewayNamespaceListerExpansion allows custom methods to be added to
// IstioGatewayNamespaceLister.
type IstioGatewayNamespaceListerExpansion interface{}

// LLMProviderListerExpansion allows custom methods to be added to
// LLMProviderLister.
type LLMProviderListerExpansion interface{}

// LLMProviderNamespaceListerExpansion allows custom methods to be added to
// LLMProviderNamespaceLister.
type LLMProviderNamespaceListerExpansion interface{}

// LLMRouteListerExpansion allows custom methods to be added to
// LLMRouteLister.
type LLMRouteListerExpansion interface{}

// LLMRouteNamespaceListerExpansion allows custom methods to be added to
// LLMRouteNamespaceLister.
type LLMRouteNamespaceListerExpansion interface{}
