// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IstioGatewayLister helps list IstioGateways.
// All objects returned here must be treated as read-only.
type IstioGatewayLister interface {
	// List lists all IstioGateways in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.IstioGateway, err error)
	// IstioGateways returns an object that can list and get IstioGateways.
	IstioGateways(namespace string) IstioGatewayNamespaceLister
	IstioGatewayListerExpansion
}

// istioGatewayLister implements the IstioGatewayLister interface.
type istioGatewayLister struct {
	indexer cache.Indexer
}

// NewIstioGatewayLister returns a new IstioGatewayLister.
func NewIstioGatewayLister(indexer cache.Indexer) IstioGatewayLister {
	return &istioGatewayLister{indexer: indexer}
}

// List lists all IstioGateways in the indexer.
func (s *istioGatewayLister) List(selector labels.Selector) (ret []*v1.IstioGateway, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.IstioGateway))
	})
	return ret, err
}

// IstioGateways returns an object that can list and get IstioGateways.
func (s *istioGatewayLister) IstioGateways(namespace string) IstioGatewayNamespaceLister {
	return istioGatewayNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// IstioGatewayNamespaceLister helps list and get IstioGateways.
// All objects returned here must be treated as read-only.
type IstioGatewayNamespaceLister interface {
	// List lists all IstioGateways in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.IstioGateway, err error)
	// Get retrieves the IstioGateway from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.IstioGateway, error)
	IstioGatewayNamespaceListerExpansion
}

// istioGatewayNamespaceLister implements the IstioGatewayNamespaceLister
// interface.
type istioGatewayNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all IstioGateways in the indexer for a given namespace.
func (s istioGatewayNamespaceLister) List(selector labels.Selector) (ret []*v1.IstioGateway, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.IstioGateway))
	})
	return ret, err
}

// Get retrieves the IstioGateway from the indexer for a given namespace and name.
func (s istioGatewayNamespaceLister) Get(name string) (*v1.IstioGateway, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("istiogateway"), name)
	}
	return obj.(*v1.IstioGateway), nil
}
