// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/api/alibabacloudservicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LLMRouteLister helps list LLMRoutes.
// All objects returned here must be treated as read-only.
type LLMRouteLister interface {
	// List lists all LLMRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LLMRoute, err error)
	// LLMRoutes returns an object that can list and get LLMRoutes.
	LLMRoutes(namespace string) LLMRouteNamespaceLister
	LLMRouteListerExpansion
}

// lLMRouteLister implements the LLMRouteLister interface.
type lLMRouteLister struct {
	indexer cache.Indexer
}

// NewLLMRouteLister returns a new LLMRouteLister.
func NewLLMRouteLister(indexer cache.Indexer) LLMRouteLister {
	return &lLMRouteLister{indexer: indexer}
}

// List lists all LLMRoutes in the indexer.
func (s *lLMRouteLister) List(selector labels.Selector) (ret []*v1.LLMRoute, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LLMRoute))
	})
	return ret, err
}

// LLMRoutes returns an object that can list and get LLMRoutes.
func (s *lLMRouteLister) LLMRoutes(namespace string) LLMRouteNamespaceLister {
	return lLMRouteNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// LLMRouteNamespaceLister helps list and get LLMRoutes.
// All objects returned here must be treated as read-only.
type LLMRouteNamespaceLister interface {
	// List lists all LLMRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LLMRoute, err error)
	// Get retrieves the LLMRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.LLMRoute, error)
	LLMRouteNamespaceListerExpansion
}

// lLMRouteNamespaceLister implements the LLMRouteNamespaceLister
// interface.
type lLMRouteNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all LLMRoutes in the indexer for a given namespace.
func (s lLMRouteNamespaceLister) List(selector labels.Selector) (ret []*v1.LLMRoute, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LLMRoute))
	})
	return ret, err
}

// Get retrieves the LLMRoute from the indexer for a given namespace and name.
func (s lLMRouteNamespaceLister) Get(name string) (*v1.LLMRoute, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("llmroute"), name)
	}
	return obj.(*v1.LLMRoute), nil
}
