// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloud-servicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMEgressTrafficPolicies implements ASMEgressTrafficPolicyInterface
type FakeASMEgressTrafficPolicies struct {
	Fake *FakeIstioV1
	ns   string
}

var asmegresstrafficpoliciesResource = v1.SchemeGroupVersion.WithResource("asmegresstrafficpolicies")

var asmegresstrafficpoliciesKind = v1.SchemeGroupVersion.WithKind("ASMEgressTrafficPolicy")

// Get takes name of the aSMEgressTrafficPolicy, and returns the corresponding aSMEgressTrafficPolicy object, and an error if there is any.
func (c *FakeASMEgressTrafficPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMEgressTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmegresstrafficpoliciesResource, c.ns, name), &v1.ASMEgressTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMEgressTrafficPolicy), err
}

// List takes label and field selectors, and returns the list of ASMEgressTrafficPolicies that match those selectors.
func (c *FakeASMEgressTrafficPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMEgressTrafficPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmegresstrafficpoliciesResource, asmegresstrafficpoliciesKind, c.ns, opts), &v1.ASMEgressTrafficPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMEgressTrafficPolicyList{ListMeta: obj.(*v1.ASMEgressTrafficPolicyList).ListMeta}
	for _, item := range obj.(*v1.ASMEgressTrafficPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMEgressTrafficPolicies.
func (c *FakeASMEgressTrafficPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmegresstrafficpoliciesResource, c.ns, opts))

}

// Create takes the representation of a aSMEgressTrafficPolicy and creates it.  Returns the server's representation of the aSMEgressTrafficPolicy, and an error, if there is any.
func (c *FakeASMEgressTrafficPolicies) Create(ctx context.Context, aSMEgressTrafficPolicy *v1.ASMEgressTrafficPolicy, opts metav1.CreateOptions) (result *v1.ASMEgressTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmegresstrafficpoliciesResource, c.ns, aSMEgressTrafficPolicy), &v1.ASMEgressTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMEgressTrafficPolicy), err
}

// Update takes the representation of a aSMEgressTrafficPolicy and updates it. Returns the server's representation of the aSMEgressTrafficPolicy, and an error, if there is any.
func (c *FakeASMEgressTrafficPolicies) Update(ctx context.Context, aSMEgressTrafficPolicy *v1.ASMEgressTrafficPolicy, opts metav1.UpdateOptions) (result *v1.ASMEgressTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmegresstrafficpoliciesResource, c.ns, aSMEgressTrafficPolicy), &v1.ASMEgressTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMEgressTrafficPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMEgressTrafficPolicies) UpdateStatus(ctx context.Context, aSMEgressTrafficPolicy *v1.ASMEgressTrafficPolicy, opts metav1.UpdateOptions) (*v1.ASMEgressTrafficPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmegresstrafficpoliciesResource, "status", c.ns, aSMEgressTrafficPolicy), &v1.ASMEgressTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMEgressTrafficPolicy), err
}

// Delete takes name of the aSMEgressTrafficPolicy and deletes it. Returns an error if one occurs.
func (c *FakeASMEgressTrafficPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmegresstrafficpoliciesResource, c.ns, name, opts), &v1.ASMEgressTrafficPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMEgressTrafficPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmegresstrafficpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMEgressTrafficPolicyList{})
	return err
}

// Patch applies the patch and returns the patched aSMEgressTrafficPolicy.
func (c *FakeASMEgressTrafficPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMEgressTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmegresstrafficpoliciesResource, c.ns, name, pt, data, subresources...), &v1.ASMEgressTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMEgressTrafficPolicy), err
}
