// Copyright 2023 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "istio.io/api/alibabacloud-servicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeASMCircuitBreakers implements ASMCircuitBreakerInterface
type FakeASMCircuitBreakers struct {
	Fake *FakeIstioV1
	ns   string
}

var asmcircuitbreakersResource = v1.SchemeGroupVersion.WithResource("asmcircuitbreakers")

var asmcircuitbreakersKind = v1.SchemeGroupVersion.WithKind("ASMCircuitBreaker")

// Get takes name of the aSMCircuitBreaker, and returns the corresponding aSMCircuitBreaker object, and an error if there is any.
func (c *FakeASMCircuitBreakers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMCircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(asmcircuitbreakersResource, c.ns, name), &v1.ASMCircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCircuitBreaker), err
}

// List takes label and field selectors, and returns the list of ASMCircuitBreakers that match those selectors.
func (c *FakeASMCircuitBreakers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMCircuitBreakerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(asmcircuitbreakersResource, asmcircuitbreakersKind, c.ns, opts), &v1.ASMCircuitBreakerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ASMCircuitBreakerList{ListMeta: obj.(*v1.ASMCircuitBreakerList).ListMeta}
	for _, item := range obj.(*v1.ASMCircuitBreakerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aSMCircuitBreakers.
func (c *FakeASMCircuitBreakers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(asmcircuitbreakersResource, c.ns, opts))

}

// Create takes the representation of a aSMCircuitBreaker and creates it.  Returns the server's representation of the aSMCircuitBreaker, and an error, if there is any.
func (c *FakeASMCircuitBreakers) Create(ctx context.Context, aSMCircuitBreaker *v1.ASMCircuitBreaker, opts metav1.CreateOptions) (result *v1.ASMCircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(asmcircuitbreakersResource, c.ns, aSMCircuitBreaker), &v1.ASMCircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCircuitBreaker), err
}

// Update takes the representation of a aSMCircuitBreaker and updates it. Returns the server's representation of the aSMCircuitBreaker, and an error, if there is any.
func (c *FakeASMCircuitBreakers) Update(ctx context.Context, aSMCircuitBreaker *v1.ASMCircuitBreaker, opts metav1.UpdateOptions) (result *v1.ASMCircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(asmcircuitbreakersResource, c.ns, aSMCircuitBreaker), &v1.ASMCircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCircuitBreaker), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeASMCircuitBreakers) UpdateStatus(ctx context.Context, aSMCircuitBreaker *v1.ASMCircuitBreaker, opts metav1.UpdateOptions) (*v1.ASMCircuitBreaker, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(asmcircuitbreakersResource, "status", c.ns, aSMCircuitBreaker), &v1.ASMCircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCircuitBreaker), err
}

// Delete takes name of the aSMCircuitBreaker and deletes it. Returns an error if one occurs.
func (c *FakeASMCircuitBreakers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(asmcircuitbreakersResource, c.ns, name, opts), &v1.ASMCircuitBreaker{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeASMCircuitBreakers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(asmcircuitbreakersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ASMCircuitBreakerList{})
	return err
}

// Patch applies the patch and returns the patched aSMCircuitBreaker.
func (c *FakeASMCircuitBreakers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMCircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(asmcircuitbreakersResource, c.ns, name, pt, data, subresources...), &v1.ASMCircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ASMCircuitBreaker), err
}
