// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"istio.io/client-go/asm/pkg/clientset/scheme"
	"net/http"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	rest "k8s.io/client-go/rest"
)

type IstioV1Interface interface {
	RESTClient() rest.Interface
	ASMAdaptiveConcurrenciesGetter
	ASMCircuitBreakersGetter
	ASMCompressorsGetter
	ASMCredentialsGetter
	ASMCustomProxyConfigInjectionTemplatesGetter
	ASMDecompressorsGetter
	ASMEgressTrafficPoliciesGetter
	ASMExtensionProvidersGetter
	ASMGlobalRateLimitersGetter
	ASMGrpcJsonTranscodersGetter
	ASMKServeConfigsGetter
	ASMKnativeConfigsGetter
	ASMLocalRateLimitersGetter
	ASMMigrateFromIstiosGetter
	ASMPacketInspectorsGetter
	ASMProxyConfigsGetter
	ASMSecurityPoliciesGetter
	ASMSwimLanesGetter
	ASMSwimLaneGroupsGetter
	EnvoyFilterTemplatesGetter
	EnvoyFilterTemplateBindingsGetter
	IstioGatewaysGetter
	LLMProvidersGetter
	LLMRoutesGetter
}

// IstioV1Client is used to interact with features provided by the istio.alibabacloud.com group.
type IstioV1Client struct {
	restClient rest.Interface
}

func (c *IstioV1Client) ASMAdaptiveConcurrencies(namespace string) ASMAdaptiveConcurrencyInterface {
	return newASMAdaptiveConcurrencies(c, namespace)
}

func (c *IstioV1Client) ASMCircuitBreakers(namespace string) ASMCircuitBreakerInterface {
	return newASMCircuitBreakers(c, namespace)
}

func (c *IstioV1Client) ASMCompressors(namespace string) ASMCompressorInterface {
	return newASMCompressors(c, namespace)
}

func (c *IstioV1Client) ASMCredentials(namespace string) ASMCredentialInterface {
	return newASMCredentials(c, namespace)
}

func (c *IstioV1Client) ASMCustomProxyConfigInjectionTemplates(namespace string) ASMCustomProxyConfigInjectionTemplateInterface {
	return newASMCustomProxyConfigInjectionTemplates(c, namespace)
}

func (c *IstioV1Client) ASMDecompressors(namespace string) ASMDecompressorInterface {
	return newASMDecompressors(c, namespace)
}

func (c *IstioV1Client) ASMEgressTrafficPolicies(namespace string) ASMEgressTrafficPolicyInterface {
	return newASMEgressTrafficPolicies(c, namespace)
}

func (c *IstioV1Client) ASMExtensionProviders() ASMExtensionProviderInterface {
	return newASMExtensionProviders(c)
}

func (c *IstioV1Client) ASMGlobalRateLimiters(namespace string) ASMGlobalRateLimiterInterface {
	return newASMGlobalRateLimiters(c, namespace)
}

func (c *IstioV1Client) ASMGrpcJsonTranscoders(namespace string) ASMGrpcJsonTranscoderInterface {
	return newASMGrpcJsonTranscoders(c, namespace)
}

func (c *IstioV1Client) ASMKServeConfigs() ASMKServeConfigInterface {
	return newASMKServeConfigs(c)
}

func (c *IstioV1Client) ASMKnativeConfigs() ASMKnativeConfigInterface {
	return newASMKnativeConfigs(c)
}

func (c *IstioV1Client) ASMLocalRateLimiters(namespace string) ASMLocalRateLimiterInterface {
	return newASMLocalRateLimiters(c, namespace)
}

func (c *IstioV1Client) ASMMigrateFromIstios() ASMMigrateFromIstioInterface {
	return newASMMigrateFromIstios(c)
}

func (c *IstioV1Client) ASMPacketInspectors() ASMPacketInspectorInterface {
	return newASMPacketInspectors(c)
}

func (c *IstioV1Client) ASMProxyConfigs(namespace string) ASMProxyConfigInterface {
	return newASMProxyConfigs(c, namespace)
}

func (c *IstioV1Client) ASMSecurityPolicies() ASMSecurityPolicyInterface {
	return newASMSecurityPolicies(c)
}

func (c *IstioV1Client) ASMSwimLanes() ASMSwimLaneInterface {
	return newASMSwimLanes(c)
}

func (c *IstioV1Client) ASMSwimLaneGroups() ASMSwimLaneGroupInterface {
	return newASMSwimLaneGroups(c)
}

func (c *IstioV1Client) EnvoyFilterTemplates(namespace string) EnvoyFilterTemplateInterface {
	return newEnvoyFilterTemplates(c, namespace)
}

func (c *IstioV1Client) EnvoyFilterTemplateBindings(namespace string) EnvoyFilterTemplateBindingInterface {
	return newEnvoyFilterTemplateBindings(c, namespace)
}

func (c *IstioV1Client) IstioGateways(namespace string) IstioGatewayInterface {
	return newIstioGateways(c, namespace)
}

func (c *IstioV1Client) LLMProviders(namespace string) LLMProviderInterface {
	return newLLMProviders(c, namespace)
}

func (c *IstioV1Client) LLMRoutes(namespace string) LLMRouteInterface {
	return newLLMRoutes(c, namespace)
}

// NewForConfig creates a new IstioV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*IstioV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new IstioV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*IstioV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &IstioV1Client{client}, nil
}

// NewForConfigOrDie creates a new IstioV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *IstioV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new IstioV1Client for the given RESTClient.
func New(c rest.Interface) *IstioV1Client {
	return &IstioV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *IstioV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
