// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/scheme"
	"context"
	"time"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ASMExtensionProvidersGetter has a method to return a ASMExtensionProviderInterface.
// A group's client should implement this interface.
type ASMExtensionProvidersGetter interface {
	ASMExtensionProviders() ASMExtensionProviderInterface
}

// ASMExtensionProviderInterface has methods to work with ASMExtensionProvider resources.
type ASMExtensionProviderInterface interface {
	Create(ctx context.Context, aSMExtensionProvider *v1.ASMExtensionProvider, opts metav1.CreateOptions) (*v1.ASMExtensionProvider, error)
	Update(ctx context.Context, aSMExtensionProvider *v1.ASMExtensionProvider, opts metav1.UpdateOptions) (*v1.ASMExtensionProvider, error)
	UpdateStatus(ctx context.Context, aSMExtensionProvider *v1.ASMExtensionProvider, opts metav1.UpdateOptions) (*v1.ASMExtensionProvider, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ASMExtensionProvider, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ASMExtensionProviderList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMExtensionProvider, err error)
	ASMExtensionProviderExpansion
}

// aSMExtensionProviders implements ASMExtensionProviderInterface
type aSMExtensionProviders struct {
	client rest.Interface
}

// newASMExtensionProviders returns a ASMExtensionProviders
func newASMExtensionProviders(c *IstioV1Client) *aSMExtensionProviders {
	return &aSMExtensionProviders{
		client: c.RESTClient(),
	}
}

// Get takes name of the aSMExtensionProvider, and returns the corresponding aSMExtensionProvider object, and an error if there is any.
func (c *aSMExtensionProviders) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMExtensionProvider, err error) {
	result = &v1.ASMExtensionProvider{}
	err = c.client.Get().
		Resource("asmextensionproviders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ASMExtensionProviders that match those selectors.
func (c *aSMExtensionProviders) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMExtensionProviderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ASMExtensionProviderList{}
	err = c.client.Get().
		Resource("asmextensionproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aSMExtensionProviders.
func (c *aSMExtensionProviders) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("asmextensionproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aSMExtensionProvider and creates it.  Returns the server's representation of the aSMExtensionProvider, and an error, if there is any.
func (c *aSMExtensionProviders) Create(ctx context.Context, aSMExtensionProvider *v1.ASMExtensionProvider, opts metav1.CreateOptions) (result *v1.ASMExtensionProvider, err error) {
	result = &v1.ASMExtensionProvider{}
	err = c.client.Post().
		Resource("asmextensionproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMExtensionProvider).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aSMExtensionProvider and updates it. Returns the server's representation of the aSMExtensionProvider, and an error, if there is any.
func (c *aSMExtensionProviders) Update(ctx context.Context, aSMExtensionProvider *v1.ASMExtensionProvider, opts metav1.UpdateOptions) (result *v1.ASMExtensionProvider, err error) {
	result = &v1.ASMExtensionProvider{}
	err = c.client.Put().
		Resource("asmextensionproviders").
		Name(aSMExtensionProvider.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMExtensionProvider).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aSMExtensionProviders) UpdateStatus(ctx context.Context, aSMExtensionProvider *v1.ASMExtensionProvider, opts metav1.UpdateOptions) (result *v1.ASMExtensionProvider, err error) {
	result = &v1.ASMExtensionProvider{}
	err = c.client.Put().
		Resource("asmextensionproviders").
		Name(aSMExtensionProvider.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMExtensionProvider).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aSMExtensionProvider and deletes it. Returns an error if one occurs.
func (c *aSMExtensionProviders) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("asmextensionproviders").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aSMExtensionProviders) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("asmextensionproviders").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aSMExtensionProvider.
func (c *aSMExtensionProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMExtensionProvider, err error) {
	result = &v1.ASMExtensionProvider{}
	err = c.client.Patch(pt).
		Resource("asmextensionproviders").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
