// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/scheme"
	"context"
	"time"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ASMKServeConfigsGetter has a method to return a ASMKServeConfigInterface.
// A group's client should implement this interface.
type ASMKServeConfigsGetter interface {
	ASMKServeConfigs() ASMKServeConfigInterface
}

// ASMKServeConfigInterface has methods to work with ASMKServeConfig resources.
type ASMKServeConfigInterface interface {
	Create(ctx context.Context, aSMKServeConfig *v1.ASMKServeConfig, opts metav1.CreateOptions) (*v1.ASMKServeConfig, error)
	Update(ctx context.Context, aSMKServeConfig *v1.ASMKServeConfig, opts metav1.UpdateOptions) (*v1.ASMKServeConfig, error)
	UpdateStatus(ctx context.Context, aSMKServeConfig *v1.ASMKServeConfig, opts metav1.UpdateOptions) (*v1.ASMKServeConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ASMKServeConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ASMKServeConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMKServeConfig, err error)
	ASMKServeConfigExpansion
}

// aSMKServeConfigs implements ASMKServeConfigInterface
type aSMKServeConfigs struct {
	client rest.Interface
}

// newASMKServeConfigs returns a ASMKServeConfigs
func newASMKServeConfigs(c *IstioV1Client) *aSMKServeConfigs {
	return &aSMKServeConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the aSMKServeConfig, and returns the corresponding aSMKServeConfig object, and an error if there is any.
func (c *aSMKServeConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMKServeConfig, err error) {
	result = &v1.ASMKServeConfig{}
	err = c.client.Get().
		Resource("asmkserveconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ASMKServeConfigs that match those selectors.
func (c *aSMKServeConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMKServeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ASMKServeConfigList{}
	err = c.client.Get().
		Resource("asmkserveconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aSMKServeConfigs.
func (c *aSMKServeConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("asmkserveconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aSMKServeConfig and creates it.  Returns the server's representation of the aSMKServeConfig, and an error, if there is any.
func (c *aSMKServeConfigs) Create(ctx context.Context, aSMKServeConfig *v1.ASMKServeConfig, opts metav1.CreateOptions) (result *v1.ASMKServeConfig, err error) {
	result = &v1.ASMKServeConfig{}
	err = c.client.Post().
		Resource("asmkserveconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMKServeConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aSMKServeConfig and updates it. Returns the server's representation of the aSMKServeConfig, and an error, if there is any.
func (c *aSMKServeConfigs) Update(ctx context.Context, aSMKServeConfig *v1.ASMKServeConfig, opts metav1.UpdateOptions) (result *v1.ASMKServeConfig, err error) {
	result = &v1.ASMKServeConfig{}
	err = c.client.Put().
		Resource("asmkserveconfigs").
		Name(aSMKServeConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMKServeConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aSMKServeConfigs) UpdateStatus(ctx context.Context, aSMKServeConfig *v1.ASMKServeConfig, opts metav1.UpdateOptions) (result *v1.ASMKServeConfig, err error) {
	result = &v1.ASMKServeConfig{}
	err = c.client.Put().
		Resource("asmkserveconfigs").
		Name(aSMKServeConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMKServeConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aSMKServeConfig and deletes it. Returns an error if one occurs.
func (c *aSMKServeConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("asmkserveconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aSMKServeConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("asmkserveconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aSMKServeConfig.
func (c *aSMKServeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMKServeConfig, err error) {
	result = &v1.ASMKServeConfig{}
	err = c.client.Patch(pt).
		Resource("asmkserveconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
