// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/scheme"
	"context"
	"time"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ASMMigrateFromIstiosGetter has a method to return a ASMMigrateFromIstioInterface.
// A group's client should implement this interface.
type ASMMigrateFromIstiosGetter interface {
	ASMMigrateFromIstios() ASMMigrateFromIstioInterface
}

// ASMMigrateFromIstioInterface has methods to work with ASMMigrateFromIstio resources.
type ASMMigrateFromIstioInterface interface {
	Create(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.CreateOptions) (*v1.ASMMigrateFromIstio, error)
	Update(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.UpdateOptions) (*v1.ASMMigrateFromIstio, error)
	UpdateStatus(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.UpdateOptions) (*v1.ASMMigrateFromIstio, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ASMMigrateFromIstio, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ASMMigrateFromIstioList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMMigrateFromIstio, err error)
	ASMMigrateFromIstioExpansion
}

// aSMMigrateFromIstios implements ASMMigrateFromIstioInterface
type aSMMigrateFromIstios struct {
	client rest.Interface
}

// newASMMigrateFromIstios returns a ASMMigrateFromIstios
func newASMMigrateFromIstios(c *IstioV1Client) *aSMMigrateFromIstios {
	return &aSMMigrateFromIstios{
		client: c.RESTClient(),
	}
}

// Get takes name of the aSMMigrateFromIstio, and returns the corresponding aSMMigrateFromIstio object, and an error if there is any.
func (c *aSMMigrateFromIstios) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMMigrateFromIstio, err error) {
	result = &v1.ASMMigrateFromIstio{}
	err = c.client.Get().
		Resource("asmmigratefromistios").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ASMMigrateFromIstios that match those selectors.
func (c *aSMMigrateFromIstios) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMMigrateFromIstioList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ASMMigrateFromIstioList{}
	err = c.client.Get().
		Resource("asmmigratefromistios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aSMMigrateFromIstios.
func (c *aSMMigrateFromIstios) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("asmmigratefromistios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aSMMigrateFromIstio and creates it.  Returns the server's representation of the aSMMigrateFromIstio, and an error, if there is any.
func (c *aSMMigrateFromIstios) Create(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.CreateOptions) (result *v1.ASMMigrateFromIstio, err error) {
	result = &v1.ASMMigrateFromIstio{}
	err = c.client.Post().
		Resource("asmmigratefromistios").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMMigrateFromIstio).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aSMMigrateFromIstio and updates it. Returns the server's representation of the aSMMigrateFromIstio, and an error, if there is any.
func (c *aSMMigrateFromIstios) Update(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.UpdateOptions) (result *v1.ASMMigrateFromIstio, err error) {
	result = &v1.ASMMigrateFromIstio{}
	err = c.client.Put().
		Resource("asmmigratefromistios").
		Name(aSMMigrateFromIstio.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMMigrateFromIstio).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aSMMigrateFromIstios) UpdateStatus(ctx context.Context, aSMMigrateFromIstio *v1.ASMMigrateFromIstio, opts metav1.UpdateOptions) (result *v1.ASMMigrateFromIstio, err error) {
	result = &v1.ASMMigrateFromIstio{}
	err = c.client.Put().
		Resource("asmmigratefromistios").
		Name(aSMMigrateFromIstio.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMMigrateFromIstio).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aSMMigrateFromIstio and deletes it. Returns an error if one occurs.
func (c *aSMMigrateFromIstios) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("asmmigratefromistios").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aSMMigrateFromIstios) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("asmmigratefromistios").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aSMMigrateFromIstio.
func (c *aSMMigrateFromIstios) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMMigrateFromIstio, err error) {
	result = &v1.ASMMigrateFromIstio{}
	err = c.client.Patch(pt).
		Resource("asmmigratefromistios").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
