// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/scheme"
	"context"
	"time"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ASMPacketInspectorsGetter has a method to return a ASMPacketInspectorInterface.
// A group's client should implement this interface.
type ASMPacketInspectorsGetter interface {
	ASMPacketInspectors() ASMPacketInspectorInterface
}

// ASMPacketInspectorInterface has methods to work with ASMPacketInspector resources.
type ASMPacketInspectorInterface interface {
	Create(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.CreateOptions) (*v1.ASMPacketInspector, error)
	Update(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.UpdateOptions) (*v1.ASMPacketInspector, error)
	UpdateStatus(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.UpdateOptions) (*v1.ASMPacketInspector, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ASMPacketInspector, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ASMPacketInspectorList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMPacketInspector, err error)
	ASMPacketInspectorExpansion
}

// aSMPacketInspectors implements ASMPacketInspectorInterface
type aSMPacketInspectors struct {
	client rest.Interface
}

// newASMPacketInspectors returns a ASMPacketInspectors
func newASMPacketInspectors(c *IstioV1Client) *aSMPacketInspectors {
	return &aSMPacketInspectors{
		client: c.RESTClient(),
	}
}

// Get takes name of the aSMPacketInspector, and returns the corresponding aSMPacketInspector object, and an error if there is any.
func (c *aSMPacketInspectors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ASMPacketInspector, err error) {
	result = &v1.ASMPacketInspector{}
	err = c.client.Get().
		Resource("asmpacketinspectors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ASMPacketInspectors that match those selectors.
func (c *aSMPacketInspectors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ASMPacketInspectorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ASMPacketInspectorList{}
	err = c.client.Get().
		Resource("asmpacketinspectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aSMPacketInspectors.
func (c *aSMPacketInspectors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("asmpacketinspectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aSMPacketInspector and creates it.  Returns the server's representation of the aSMPacketInspector, and an error, if there is any.
func (c *aSMPacketInspectors) Create(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.CreateOptions) (result *v1.ASMPacketInspector, err error) {
	result = &v1.ASMPacketInspector{}
	err = c.client.Post().
		Resource("asmpacketinspectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMPacketInspector).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aSMPacketInspector and updates it. Returns the server's representation of the aSMPacketInspector, and an error, if there is any.
func (c *aSMPacketInspectors) Update(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.UpdateOptions) (result *v1.ASMPacketInspector, err error) {
	result = &v1.ASMPacketInspector{}
	err = c.client.Put().
		Resource("asmpacketinspectors").
		Name(aSMPacketInspector.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMPacketInspector).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aSMPacketInspectors) UpdateStatus(ctx context.Context, aSMPacketInspector *v1.ASMPacketInspector, opts metav1.UpdateOptions) (result *v1.ASMPacketInspector, err error) {
	result = &v1.ASMPacketInspector{}
	err = c.client.Put().
		Resource("asmpacketinspectors").
		Name(aSMPacketInspector.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aSMPacketInspector).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aSMPacketInspector and deletes it. Returns an error if one occurs.
func (c *aSMPacketInspectors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("asmpacketinspectors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aSMPacketInspectors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("asmpacketinspectors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aSMPacketInspector.
func (c *aSMPacketInspectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ASMPacketInspector, err error) {
	result = &v1.ASMPacketInspector{}
	err = c.client.Patch(pt).
		Resource("asmpacketinspectors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
