// Copyright 2025 Alibaba Cloud Service Mesh
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "istio.io/client-go/asm/pkg/clientset/scheme"
	"context"
	"time"

	v1 "istio.io/api/alibabacloudservicemesh/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LLMRoutesGetter has a method to return a LLMRouteInterface.
// A group's client should implement this interface.
type LLMRoutesGetter interface {
	LLMRoutes(namespace string) LLMRouteInterface
}

// LLMRouteInterface has methods to work with LLMRoute resources.
type LLMRouteInterface interface {
	Create(ctx context.Context, lLMRoute *v1.LLMRoute, opts metav1.CreateOptions) (*v1.LLMRoute, error)
	Update(ctx context.Context, lLMRoute *v1.LLMRoute, opts metav1.UpdateOptions) (*v1.LLMRoute, error)
	UpdateStatus(ctx context.Context, lLMRoute *v1.LLMRoute, opts metav1.UpdateOptions) (*v1.LLMRoute, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.LLMRoute, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.LLMRouteList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LLMRoute, err error)
	LLMRouteExpansion
}

// lLMRoutes implements LLMRouteInterface
type lLMRoutes struct {
	client rest.Interface
	ns     string
}

// newLLMRoutes returns a LLMRoutes
func newLLMRoutes(c *IstioV1Client, namespace string) *lLMRoutes {
	return &lLMRoutes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the lLMRoute, and returns the corresponding lLMRoute object, and an error if there is any.
func (c *lLMRoutes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LLMRoute, err error) {
	result = &v1.LLMRoute{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("llmroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LLMRoutes that match those selectors.
func (c *lLMRoutes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LLMRouteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.LLMRouteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("llmroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested lLMRoutes.
func (c *lLMRoutes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("llmroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a lLMRoute and creates it.  Returns the server's representation of the lLMRoute, and an error, if there is any.
func (c *lLMRoutes) Create(ctx context.Context, lLMRoute *v1.LLMRoute, opts metav1.CreateOptions) (result *v1.LLMRoute, err error) {
	result = &v1.LLMRoute{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("llmroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lLMRoute).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a lLMRoute and updates it. Returns the server's representation of the lLMRoute, and an error, if there is any.
func (c *lLMRoutes) Update(ctx context.Context, lLMRoute *v1.LLMRoute, opts metav1.UpdateOptions) (result *v1.LLMRoute, err error) {
	result = &v1.LLMRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("llmroutes").
		Name(lLMRoute.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lLMRoute).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *lLMRoutes) UpdateStatus(ctx context.Context, lLMRoute *v1.LLMRoute, opts metav1.UpdateOptions) (result *v1.LLMRoute, err error) {
	result = &v1.LLMRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("llmroutes").
		Name(lLMRoute.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lLMRoute).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the lLMRoute and deletes it. Returns an error if one occurs.
func (c *lLMRoutes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("llmroutes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *lLMRoutes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("llmroutes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched lLMRoute.
func (c *lLMRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LLMRoute, err error) {
	result = &v1.LLMRoute{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("llmroutes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
